### PR TITLE
Snow Land by Elvis26 (Updated)

### PR DESCRIPTION
**Pull request by RyanZem**
Added a train track, blue's and red's flags, planted some trees, built some houses, MOVED red's base to a better position, added path to some buildings, also updated the map description, placed snow on some buildings.

### CODE REVIEW

**Comment by MoreKat** [comment]
An actual good enhancement for this map would be to add coal ores in the mine, haven't tested yet, just a suggestion.

**Comment by RyanZem** [comment]
> An actual good enhancement for this map would be to add coal ores in the mine, haven't tested yet, just a suggestion.

Oh, yes I just forgot to add it in the mine in this update. Thanks for suggesting :)

**Comment by RyanZem** [comment]
> > An actual good enhancement for this map would be to add coal ores in the mine, haven't tested yet, just a suggestion.
> 
> Oh, yes I just forgot to add it in the mine in this update. Thanks for suggesting :)

I added 20 coal ore on 2 sides.

**Review by MoreKat — APPROVED** [review]

**Comment by MoreKat** [comment]
Closing this in favour of #263

**Pull request closed without merging**
