### PR TITLE
Add "The Mines Of Vexillum" map

### PR DESCRIPTION
**Pull request by DragoniEU**
The `default:dirt` is just a placeholder, initial items are up for discussion.

The Mines Of Vexillum contains custom trees, mese and diamond ores, vast iron veins (thanks to KGM who coded them) and a couple coal ores, as well as lots of lava.

(It may be a little asymetrical, but it's still fair. I made sure that there are equal amounts of diamond and mese ores on both sides).

Enjoy!
screenshot_20211023_232633

### CODE REVIEW

**Comment by farooqkz** [comment]
The map seems really fun.
What changes are required before it can be merged?

**Comment by HobbitPower** [comment]
@DragoniEU If you are still interested: The conf file is incomplete and needs to be adapted to CTF v3. Since then CTF has its own integrated map editor, important hints for map creation can be found in the pinned messages in the #maps channel on the CTF Discord or here: [README.md](https://github.com/MT-CTF/capturetheflag/tree/master/mods/ctf/ctf_map#ctf-map---map-maker). WorldEdit is recommended, especially in your case.
At a glance, almost everything is missing in the conf-File from team zones, chest zones, flag positions, etc. So if you are interested in updating the map to a working v3 variant, please let me know. Otherwise we can't approve it or test it at all.

**Comment by farooqkz** [comment]
> @DragoniEU If you are still interested: The conf file is incomplete and needs to be adapted to CTF v3. Since then CTF has its own integrated map editor, important hints for map creation can be found in the pinned messages in the #maps channel on the CTF Discord or here: [README.md](https://github.com/MT-CTF/capturetheflag/tree/master/mods/ctf/ctf_map#ctf-map---map-maker). WorldEdit is recommended. At a glance, almost everything is missing in the conf-File from team zones, chest zones, flag positions, etc. So if you are interested in updating the map to a working v3 variant, please let me know. Otherwise we can't approve it or test it at all.

The author seems to be gone. If you agree, I might want to finish the job if you agree.

**Comment by HobbitPower** [comment]
> > The author seems to be gone. If you agree, I might want to finish the job if you agree.
> 
> When I pinged them in #maps they were still around, but they left in the meantime. I have sent them another message via PM. I will let you know if they are willing to work on it or not. So they should have the chance first, since its their map ^^

@farooqkz they will try to convert it. If the situation changes, I'll let you know.

**Comment by HobbitPower** [comment]
Okay @farooqkz , your time to shine. They have changed their mind. 

If you feel up to it, you can convert the map. I would recommend to adapt only the map itself to v3 and not to change anything else in the original map. So that we can all test the original map, further changes can then be discussed in the review process.
I've already had a rough look at the map, I could also convert the map if necessary. But since you offered it: here you go. If there are any difficulties, let me know. I can also convert it then.

**Comment by farooqkz** [comment]
> Okay @farooqkz , your time to shine. They have changed their mind.
> 
> If you feel up to it, you can convert the map. I would recommend to adapt only the map itself to v3 and not to change anything else in the original map. So that we can all test the original map, further changes can then be discussed in the review process. I've already had a rough look at the map, I could also convert the map if necessary. But since you offered it: here you go. If there are any difficulties, let me know. I can also convert it then.

I don't shine I am just a regular lamp xD

Hopefully there is no time set for this as I am busy with many many other stuff for now.

**Comment by HobbitPower** [comment]
> Hopefully there is no time set for this as I am busy with many many other stuff for now.

I will ask again in some weeks/months ;)

**Comment by farooqkz** [comment]
I will try to find some time for it in the coming days.

**Comment by HobbitPower** [comment]
Closing this PR, see #323

**Pull request closed without merging**
