### PR TITLE
Lava Puddles Map Debug

### PR DESCRIPTION
**Pull request by Avyukt1**
There was a small bug in my map `Lava Puddles` And I have made changes and tested it. Its important to merge it before my map is updated in the server.

### CODE REVIEW

**Comment by JostP** [comment]
What is that bug?

**Comment by Avyukt1** [comment]
> What is that bug?

There is Indestructible Ladder on the brick wall for one base and nothing such thing on the other.

**Comment by JostP** [comment]
> > What is that bug?
> 
> There is Indestructible Ladder on the brick wall for one base and no such thing on the other.

Ok will merge today.
Map is already on server btw. But this bug is not that big problem as you said.

**Review by JostP — APPROVED** [review]
Looks good :+1:

**Pull request merged**
