### PR TITLE
Volcano Fix red border bug

### PR DESCRIPTION
**Pull request by ksandronline**
Fix red border bug
Im add red border to insise team zone for both team.
https://discord.com/channels/447819017391046687/915304240690393138/955928779048513576

### CODE REVIEW

**Comment by MoreKat** [comment]
@ksandronline this PR shouldn't add the Soccer Stadium map, same for your PR about the Wonderland map.

**Comment by ksandronline** [comment]
> @ksandronline this PR shouldn't add the Soccer Stadium map, same for your PR about the Wonderland map.

I saw the problem. I do not know how to do it correctly, I thought it was necessary to make a separate branch, but it turned out to be wrong. I will wait for the release of Soccer stadium and after that I will make megre. If it can be done better and easier, and you are ready to help me, I will be grateful.

**Comment by ksandronline** [comment]
can I clarify that the Volcano and Wonderland queries cannot be fixed and need to be deleted. And create a new branch based on the commit before the soccer stadium map was added? There is also a question about Soccer stadium, is it designed correctly, does it need to be redone?

**Comment by ksandronline** [comment]
see #247

**Pull request closed without merging**
