### PR TITLE
Add "mulu_hills" map by winniepee0

### PR DESCRIPTION
**Pull request by winniepee**

### CODE REVIEW

**Comment by Thomas--S** [comment]
License missing

**Comment by winniepee** [comment]
screenshot

**Comment by AnyBlue** [comment]
@winniepee Change name of Mulu Hills.png on screenshot.png

**Comment by Elvis-26** [comment]
Add Licence

**Comment by JostP** [comment]
PR must contain only 3 new files inside one folder. You currently have 3 inside folder and 3 outside, so 6 files.

**Comment by winniepee** [comment]
gonna change some files

**Pull request closed without merging**
