### PR TITLE
Abandoned Battlefield Update (CTFv3 update: 4 Teams Map)

### PR DESCRIPTION
**Pull request by HobbitPower**
* updated map for CTFv3
* turned the old map into a 4 Teams Map (added second red barrier, made 2 more shelters breakable)
* few changes to the map (new ground in the middle, added 4 bigger flags, partly prevented tunneling)

### CODE REVIEW

**Comment by olliy1or** [comment]
I like this update
now you can actually get out of the water even if you don't have blocks lol
Maybe the two teams on each other might target each other before going to the other side though :thinking:. but i like it, looks alright

**Review by olliy1or — APPROVED** [review]

**Comment by LoneWolfHT** [comment]
Make sure you provide ores if you want to enable this for `classic`

**Comment by HobbitPower** [comment]
> Make sure you provide ores if you want to enable this for `classic`

i would have to add 2 more mines + reopen the other 2 (i closed the current ones). not the biggest effort but right now i am fine with just enabling the classes + nade mode ^^

**Review by MoreKat — APPROVED** [review]
Nice! My only remark is that it might be a bit too dark, with the skybox. It shouldn't be a problem unless players complain about it, then you might have to take action.

**Pull request merged**
