### PR TITLE
new map: plain 3

### PR DESCRIPTION
**Pull request by farooqkz**
It's a 3 team map.

### CODE REVIEW

**Comment by LuismiInTheZone** [comment]
> It's a 3 team map.

Emm, where's the barrier?!?!?

**Comment by HobbitPower** [comment]
(This is not my final review)
* barriers are missing (outer barriers + red barriers). So make sure you place them + control the team zones and corners (you have to include the outer barriers)
* you spawn inside the mese lamps, so take a look if you placed the flags correctly
* take another look at the chestzones, I got an error there (most chests were not loaded)
* your chests contains unknown items. Probably you have to check the treasures again

**Comment by farooqkz** [comment]
All issues except the chest zones should've been solved.

**Comment by farooqkz** [comment]
What do I do regarding these?
image

**Comment by farooqkz** [comment]
> All issues except the chest zones should've been solved.

I need help solving these:

 - I think the flags are set correctly but I still spawn inside blocks.
 - The barriers are not removed upon game start.

**Comment by LuismiInTheZone** [comment]
I've tested this again and look:

- I can cross a bit to the other team, so if I have noclip or whatever I can cross and nothing will happen, I'll stay there
- If I build up towards the ceiling it will say to me that I can't cross the barrier without starting, strange because there's a lot more of space

In general you fixed lot of things

**Comment by LuismiInTheZone** [comment]
Also I just saw this now, blue team can take mese blocks before other teams

**Comment by farooqkz** [comment]
I've made an update. Now the issues @LuismiInTheZone talked about must be solved.

However,
 - There are still many unknown items in the chests.
 - The chests are not spawned correctly.
 - The barrier between red and blue is not removed upon match start/

**Comment by LuismiInTheZone** [comment]
You still having 3 problems at the map:

- One barrier of the two disappear after the time but the other don't, so I can't cross to the other teams to capture
- Team blue has got 2 mese blocks, while others only have 1
- Chests can't spawn correctly

**Comment by farooqkz** [comment]
Regarding the 2nd problem, it has been solved. The blue team doesn't have access to those mese blocks till the match starts and when it does, all teams will have access to those blocks.

**Comment by HobbitPower** [comment]
> I've made an update. Now the issues @LuismiInTheZone talked about must be solved.
> 
> However,
> 
> * There are still many unknown items in the chests.
> * The chests are not spawned correctly.
> * The barrier between red and blue is not removed upon match start/

Try the following:
* Look at your conf-file at delete everything beginning with the between the """ (so including the """ from line 17 and 31. then copy this into line 17 (treasures): 

> default:pick_diamond;1;1;5;0.05;1;default:pick_mese;1;1;5;0.05;1;default:axe_mese;1;1;5;0.05;1;default:axe_diamond;1;1;5;0.05;1;default:sword_steel;1;1;10;0.05;1;default:sword_mese;1;1;5;0.02;1;default:sword_diamond;1;1;5;0.02;1;ctf_ranged:pistol_loaded;1;1;5;0.1;1;ctf_ranged:rifle_loaded;1;1;5;0.1;1;grenades:frag;1;1;5;0.3;1;grenades:smoke;1;1;5;0.6;1;default:cobble;30;60;5;0.6;1; 

It had problems with the """ + you wrote granades instead of grenades once. That should fix the unknown items problem.

* The chest spawning problem: I have increased the y-coordinate from every pos2 by 1. that worked. You can copy the following and replace what you have wrote in line 4 (chests).

>  return {{pos2={y=27.5,x=53,z=55},pos1={y=26.5,x=30,z=2},amount=42},{pos2={y=16.5,x=23,z=55},pos1={y=15.5,x=3,z=2},amount=42},{pos2={y=3.5,x=46,z=56},pos1={y=2.5,x=38,z=3},amount=42},{pos2={y=16.5,x=81,z=55},pos1={y=15.5,x=61,z=2},amount=42}}
The only new "issue" now: Chests spawn directly above lava. You can change that with changing the x + z coordinates of the chest zones. So you would have to make the chest zones a bit smaller. If you don't have a problem with chests above lava, just keep it.

* The one red barrier problem: I haven't tried it, but afaik you need to set the whole map as the barrier region/area because you have more than one red barrier. Try that and tell me if that worked.

**Comment by farooqkz** [comment]
Thanks to @HobbitPower the problems have been solved. Also many other issues which I had forgotten to solve them has been solved as well and the frag grenade is more rare now.

**Comment by LuismiInTheZone** [comment]
> Thanks to @HobbitPower the problems have been solved. Also many other issues which I had forgotten to solve them has been solved as well and the frag grenade is more rare now.

1.  What!!!!! Why are chests kinda crazy!!! I looked and I found 7 shotguns in one team... Also I can open some chests but others I can't.
2. Are really frag grenades rare... Because I also found 3 grenades in a chest
3. Blue team still having 2 mese blocks...

**Comment by farooqkz** [comment]
> > Thanks to @HobbitPower the problems have been solved. Also many other issues which I had forgotten to solve them has been solved as well and the frag grenade is more rare now.
> 
>     1. What!!!!! Why are chests kinda crazy!!! I looked and I found 7 shotguns in one team... Also I can open some chests but others I can't.
> 
>     2. Are really frag grenades rare... Because I also found 3 grenades in a chest
> 
>     3. Blue team still having 2 mese blocks...

1. my fault. I think I haven't fully understand the format of treasures. Can you send a PR to my repo?
2. Same as above
3. May I ask where are these 2 mese blocks for blue and how are they accessible before match starts?

**Comment by LuismiInTheZone** [comment]
> > > Thanks to @HobbitPower the problems have been solved. Also many other issues which I had forgotten to solve them has been solved as well and the frag grenade is more rare now.
> > 
> > 
> > ```
> > 1. What!!!!! Why are chests kinda crazy!!! I looked and I found 7 shotguns in one team... Also I can open some chests but others I can't.
> > 
> > 2. Are really frag grenades rare... Because I also found 3 grenades in a chest
> > 
> > 3. Blue team still having 2 mese blocks...
> > ```
> 
> 1. my fault. I think I haven't fully understand the format of treasures. Can you send a PR to my repo?
> 2. Same as above
> 3. May I ask where are these 2 mese blocks for blue and how are they accessible before match starts?

repo? I don't know how to fix your chest problem, I have never see before this, except in one map... I could take it, look at it and tell you later what's wrong...

2nd thing: 

https://user-images.githubusercontent.com/83732589/209796529-d0100972-5fd4-4c10-9714-d9754883d435.mov

**Comment by farooqkz** [comment]
Ah yes that's true, I think I will move the barriers and make it impossible for the blue to go down while the match has not started yet. Thank you :)

**Comment by farooqkz** [comment]
The problems have been solved except that many chests still don't show anything when you rightclick on them.

**Comment by LuismiInTheZone** [comment]
Most of problems are ok now, chests work for me at least, but you have a little problem, I can't go to the border of the map before starting, if I stand in some block of the nearest one from some barrier it kicks me to the flag again (I hope you undestand what I'm saying...)

**Comment by farooqkz** [comment]
> Most of problems are ok now, chests work for me at least, but you have a little problem, I can't go to the border of the map before starting, if I stand in some block of the nearest one from some barrier it kicks me to the flag again (I hope you undestand what I'm saying...)

Solved.

**Comment by LuismiInTheZone** [comment]
Everything looks ok now, just need to be checked (but at license I don't think the ''or later'' is necessary)

**Comment by ColorBlob** [comment]
Nice 3 team map.
The only small issues I found are
1. A few chests still won't open
2. License doesn't need to include "or later"
3. Screenshot ratio is not 2:3

Personally, I think the teams are highly unbalanced. Team blue is higher than the other teams, which gives the other teams advantages when capturing. For team blue members to return to their base after taking the flag, they have to climb the stairs or build all the way up, which is slow. As for team red/green members trying to return to their base after taking blue's flag, all they have to do is jump down:

https://user-images.githubusercontent.com/88883098/211486640-496170b0-abc8-472f-8d87-b0803f8787a6.mp4

The size of the map is also very small, which doesn't help at all. The player just has to block spam to protect themselves, take team blue's flag, jump down onto a chest or pre-built platform, and bam, blue is no more. **All of that can be done within 8 seconds.**
Since team blue is adjacent to both the other two teams, that is extremely likely to happen ^^

Instead of attacking each other, team red and green are more likely to attack team blue at the same time after the match starts because blue is so much closer and easier.

So if you are on team blue u r ded.

**Comment by farooqkz** [comment]
@ColorBlob Thank you for the feedback. Regarding that some chests don't open up, I really don't have any idea why.

Regarding teams being unbalanced, I was hoping that the height and the lava pull will prevent easy capturing the blue flag. But the video you've just sent seems to suggest otherwise.

TBH, I had such an idea in mind but perhaps I haven't implemented it well. Do you think if I make the blue higher and scale up the map, it would be better? Alternatively, I could increase gravity to increase fall damage. That'll prevent people from jumping from the blue platform.

**Comment by ColorBlob** [comment]
I think you should increase the height of blue, together with the size of the lava pool. Increasing the distance between blue and red will help a lot. If you only increase the height, a simple pillar of ladder will do the trick and avoid fall damage.

**Comment by farooqkz** [comment]
@HobbitPower I disagree with my idea hasn't been implemented well and rather poorly. But do you think the idea might be good and worth giving a try? I want to work on this map when I get my interest back.

**Comment by HobbitPower** [comment]
@farooqkz Okay.
It's up to you. I find 3-teams generally difficult to build (but also interesting) and I still think that the middle team, in its current form, has a significant disadvantage and that the size of the map can potentially lead to very fast rounds. 
I don't want to take away your enjoyment of map building, so of course feel free to keep working on your map and incorporating feedback from others. Should I label it as WIP until then?

**Comment by HobbitPower** [comment]
> Well I am interested in having a map with odd number of teams. Do you think a triangular map would be better as a 3 team map?

You have to keep in mind that e.g. the team zones etc. have to be cubic.

**Comment by farooqkz** [comment]
> > Well I am interested in having a map with odd number of teams. Do you think a triangular map would be better as a 3 team map?
> 
> You have to keep in mind that e.g. the team zones etc. have to be cubic.

What if they didn't have to be cubic?

**Comment by LoneWolfHT** [comment]
> What if they didn't have to be cubic? ping @LoneWolfHT 

That's a confusing question.
They're cubic for simplicity and code speed.

If you can completely prevent players from getting past the barrier then it doesn't matter if the team zones match the barriers

**Comment by LuismiInTheZone** [comment]
But... is suppose to be of cubes... I don't know if there's something else

**Comment by farooqkz** [comment]
> > What if they didn't have to be cubic? ping @LoneWolfHT
> 
> That's a confusing question. They're cubic for simplicity and code speed.
> 
> If you can completely prevent players from getting past the barrier then it doesn't matter if the team zones match the barriers

Aren't team zones important also for placement of doors and traps?

**Comment by LoneWolfHT** [comment]
> > > What if they didn't have to be cubic? ping @LoneWolfHT
> > 
> > That's a confusing question. They're cubic for simplicity and code speed.
> > 
> > If you can completely prevent players from getting past the barrier then it doesn't matter if the team zones match the barriers
> 
> Aren't team zones important also for placement of doors and traps?
> 

Overlap of or space between team zones is fine, but make sure their base and a decent surrounding area is covered, they don't cover the bases/surrounding areas of other teams, and if you're left with deadzones that no teams can place in try to make that evident in your map design

**Comment by HobbitPower** [comment]
@farooqkz Your PR has become quite messed up due to the recent changes. I'll also ask again: Will you be working on this map in the near future or can we close this PR?

**Pull request closed without merging**
