### PR TITLE
Add updated version of Snow Land by Elvis26

### PR DESCRIPTION
**Pull request by MoreKat**
Creating this PR to replace #231 , which has conflicts.

### CODE REVIEW

**Comment by magnetar47** [comment]
FOV of the screenshot isn't great for using as a screenshot, IMO. But this can be fixed later also.

**Comment by MoreKat** [comment]
> FOV of the screenshot isn't great for using as a screenshot, IMO. But this can be fixed later also.

Done

**Comment by magnetar47** [comment]
> > FOV of the screenshot isn't great for using as a screenshot, IMO. But this can be fixed later also.
> 
> Done

There's still a lot of distortion (especially around the edges) in the screenshot. FOV still looks about 90-ish. I'd say the ideal FOV for screenshots is 72, which is the default FOV (however, a *little* more than that should be okay as well).

Disclaimer: Just saying what I feel - you're welcome to retain this screenshot. :)

**Comment by MoreKat** [comment]
> > > FOV of the screenshot isn't great for using as a screenshot, IMO. But this can be fixed later also.
> > 
> > 
> > Done
> 
> There's still a lot of distortion (especially around the edges) in the screenshot. FOV still looks about 90-ish. I'd say the ideal FOV for screenshots is 72, which is the default FOV (however, a _little_ more than that should be okay as well).
> 
> Disclaimer: Just saying what I feel - you're welcome to retain this screenshot. :)

My FOV was 72 when I took this screenshot. I'll give it another go.

**Comment by magnetar47** [comment]
> > > > FOV of the screenshot isn't great for using as a screenshot, IMO. But this can be fixed later also.
> > > 
> > > 
> > > Done
> > 
> > 
> > There's still a lot of distortion (especially around the edges) in the screenshot. FOV still looks about 90-ish. I'd say the ideal FOV for screenshots is 72, which is the default FOV (however, a _little_ more than that should be okay as well).
> > Disclaimer: Just saying what I feel - you're welcome to retain this screenshot. :)
> 
> My FOV was 72 when I took this screenshot. I'll give it another go @magnetar47 Do you find this one better? screenshot

Oh, that's interesting. I still find it distorted the same amount. Maybe the camera angle is tricking me. This should be fine then. 👍

**Review by HobbitPower — APPROVED** [review]
Working fine. And finally there is enough coal to mine.

**Pull request merged**
