### PR TITLE
Add new map "Appleton" by oMikekiMo

### PR DESCRIPTION
**Pull request by HobbitPower**
Note: The map creator used steel trap doors.
[LV mentioned](https://github.com/MT-CTF/maps/pull/276#issuecomment-1407753944) that he must first add a code that prevents trap doors from being picked up. 
Edit: Problem solved

### CODE REVIEW

**Comment by omikekimo** [comment]
I am gonna remove the trap doors as it makes no odds to the level really, are the wooden ones ok?

**Comment by LoneWolfHT** [comment]
> I am gonna remove the trap doors as it makes no odds to the level really, are the wooden ones ok?

Yes, I think so

**Comment by LoneWolfHT** [comment]
> LV mentioned that he must first add a code that prevents trap doors from being picked up.

Just making sure this is clear: Before this map can be merged *I* must first add a code that prevents trap doors from being picked up.
I'll wait until it's ready to be merged before doing anything though

**Comment by ColorBlob** [comment]
(This is a pretty big map so this is probably not my final review)

- The outer glass barrier looks weird. Some parts are extruding, and certain places contain a slice of water and sand. 
- I counted the ores and ore-blocks. Unless I missed something, the ores for each team are highly unbalanced. 

(The rest is personal opinion)
- I think you should give players more torches. The map contains a lot of caves and dark buildings. The 15 torches burns out quickly once you start exploring.
- Since this map encourages digging, then I recommend you to give the player an iron pickaxe or mese pickaxe as a default item. The stone pickaxe is slow and breaks easily. 
- Since this map encourages digging, I also think it would be better if red stone barriers (they turn into normal stone blocks after match starts) are added underground at the boarders. This way, there would be a underground barrier for people who are tunneling too.

**Comment by LuismiInTheZone** [comment]
Personal opinion: I found one place with... 30 mese blocks???? don't you think that's to much?

**Comment by LuismiInTheZone** [comment]
And after trying to count your ores...

I think you need to delete something:

team red: 548 diamonds... 94 mese blocks... 72 mese ores... 92 diamond blocks?????
team blue: 124 diamond... 20 mese blocks... 79 mese ores... 7 diamond blocks?????

**Comment by omikekimo** [comment]
I take the point about ores and things, better balance is probably needed so perhaps deleting some would be good, i am not however seeing the problems with the glass, it all looks ok when i fly round it, is it possible to get some screenshots so i can compare it to what i am seeing? on this end it just loos like a big glass box that is 1 node thick all the way round.

**Comment by ColorBlob** [comment]
I checked the barriers again. It's totally fine. My bad, something must have been wrong with the world I used to test your map.

**Comment by omikekimo** [comment]
That is good to know, however what you said echoed something LandarVargan said on discord in #maps, :

LandarVargan — 25/01/2023 21:58
The barrier glass should be 1 node thick, and I'll need to add some code that prevents picking up trapdoors

so it must have looked weird in that instance too. I have no idea why it would but if you both saw weirdness then something weird might be going on.

**Comment by LoneWolfHT** [comment]
> so it must have looked weird in that instance too. I have no idea why it would but if you both saw weirdness then something weird might be going on.

I had loaded your map previously, so it may have just been an issue with my world saving the old version. You can ignore it for now

**Comment by farooqkz** [comment]
I feel like this map is too big for the current population of CTF most of the time. I suggest using this map only when https://github.com/MT-CTF/capturetheflag/issues/1128 is solved. Then the map will be launched only when enough players are online. Also the treasure chests are too sparse.

**Review by MoreKat — COMMENTED** [review]
It is true that it is quite a big map. I wouldn't make it smaller but I would combat this by increasing the phys_speed, to 1.5 or so, you should experiment with this and pick what feels right. I find the ores quite hard to find, the whole tunnel system is confusing, kind like a maze. So maybe add a clear hint or move them to a more accessible location, perhaps less far down. The map is incredibly deep, I don't really see what the upside of that is. You can still have an elaborate tunneling system without forcing people to spend ages going up/down ladders, lol. Another suggestion is to add ways people can access the roofs of the buildings, such as fire escapes. 

EDIT: the abundance of ores doesn't bother me, this is a choice that the map maker can make.

**Comment by farooqkz** [comment]
> It is true that it is quite a big map. I wouldn't make it smaller but I would combat this by increasing the phys_speed, to 1.5 or so, you should experiment with this and pick what feels right. I find the ores quite hard to find, the whole tunnel system is confusing, kind like a maze. So maybe add a clear hint or move them to a more accessible location, perhaps less far down. The map is incredibly deep, I don't really see what the upside of that is. You can still have an elaborate tunneling system without forcing people to spend ages going up/down ladders, lol. Another suggestion is to add ways people can access the roofs of the buildings, such as fire escapes.
> 
> EDIT: the abundance of ores doesn't bother me, this is a choice that the map maker can make.

I believe these conditions are not enough to make the map fun. There must also be more player/block density. We can further discuss this in the appropriate issue.

**Comment by omikekimo** [comment]
Thank you for your feedback guys, some really useful stuff in here I will act on, I love the fire escapes idea and I didn't even know I could increase the physics speed, I assume that will make people run faster? I want this to be a fast paced map so I will incorporate the speed adjustment and increase the vertical routes above ground. I think a more powerful default load-out is also a must, especially a better pick axe at spawn. I am going to reduce the ores somewhat so its fair for both sides, can anyone think of anything else I might want to address?

**Comment by omikekimo** [comment]
Thank you for uploading this for me HobbitPower, and thank you to everybody who has provided feedback. I took everything on board in an effort to make this a fun fast map and I hope you can see your influence in this new version.

**Comment by MoreKat** [comment]
Why is game_modes empty? That doesn't seem right.

**Comment by MoreKat** [comment]
> It's not right, they should all be switched on. ADHD is such fun. Will I have to revert to 5.6 to save that? I upgraded my client after i finished this map.

You can just edit the map.conf manually. It should say `game_modes = return {"classic", "classes", "nade_fight"}`

**Comment by HobbitPower** [comment]
> return {"classic", "classes", "nade_fight"}

Done, @omikekimo 
I assume you want to make the map available for all modes. If not, let me know and I'll change it.

**Comment by HobbitPower** [comment]
btw I am against adding a shotgun as an initial item, so I would suggest that we remove that in the conf file. @omikekimo

**Comment by omikekimo** [comment]
Thank you @HobbitPower, you are a scholar and a gentleman.  As for the shotgun in the initial items, I'd be happy to remove it if you're dead set against that sort of thing. Would you be able to change it to be 30 ladders for me, i think that would be a useful thing for players to have on this map.

**Review by MoreKat — COMMENTED** [review]
I think the map has already been improved by a lot. I have some other remarks though. First of all, this speed (2.1) is way too fast. Your map will be over in no time, especially in classic. I also think you need to add a hint or make it easier to find the ores because it currently is quite hard.  I didn't count the ores but I assume you put the same amount on each side? A hint mentioning something about using the tunnels would also be good, as the players might not know about the elaborate tunnel system they can use. Other than that, it's a cool map and I expect it to be fun to play.

**Comment by omikekimo** [comment]
I think if I recall correctly I removed the ores mostly and evened out the distribution. I will check that and review the speed, i am sure i took care of the ores but it was a while ago. I am glad you like the map I hope everyone has fun with it. I think the hint should be "This empty town holds some deep secrets."

**Comment by omikekimo** [comment]
I have just checked ad it seems I did bring the ore count down significantly and distributed them more fairly for each team, I don't know how to count them but I think there's a similar number by the looks of it. I had a play with the speed too and i found that 1.8 still gives a good sense of speed but you run out of sprint before you get to the middle so that might be a better fit. If that can be done just by editing the .conf perhaps I could ask @HobbitPower to change the move speed to 1.8 and change the hint to read "This empty town holds some deep secrets." for me when you get a moment. Thank you to everyone who has given me feedback to make this better, i have been enjoying CTF for years and it is exciting to be able to give something back.

**Comment by MoreKat** [comment]
> I have just checked ad it seems I did bring the ore count down significantly and distributed them more fairly for each team, I don't know how to count them but I think there's a similar number for each team by the looks of it. I had a play with the speed too and i found that 1.8 still gives a good sense of speed but you run out of sprint before you get to the middle so that might be a better fit. If that can be done just by editing the .conf perhaps I could ask @HobbitPower to change the move speed to 1.8 and change the hint to read "This empty town holds some deep secrets." for me when you get a moment. Thank you to everyone who has given me feedback to make this better, i have been enjoying CTF for years and it is exciting to be able to give something back.

I'm afraid 1.8 will still be too fast. We had a map with 1.5 and matches ended quick, even though it was a four team map. I would start off with a lower speed, maybe like 1.25. We can easily adjust it after it gets added in-game if it turns out to be necessary.

**Comment by omikekimo** [comment]
If you think so then I'm happy for that to be the speed, I will defer to wisdom.  I just tried it out and it still gives a bit of oomph, especially with the extra jump and you run out of sprint as you get to the main road from spawn which is all I wanted to ensure. Plus I am a doom player and doomguy runs very fast so I might just be slightly biased. So yeah I'm happy with 1.25

**Comment by a-blob** [comment]
I agree, the current speed is way too fast. Walking around the map feels like flying.
Otherwise, I really like the map. A lot of effort is definitely spent on it. The builds look good and I didn’t find any bugs. It would be nice to finally see this map added to the game.
I don’t think the ores needs to be the exact same amount for each team, but I tried counting with World Edit and they seem to differ a lot. Team red has 200 diamond ores with 65 diamond blocks. Team blue only has 61 diamond ores and 13 diamond blocks. Team red has 65 mese ores and 97 mese blocks. While team blue has 71 mese ores and 20 mese blocks.

**Comment by omikekimo** [comment]
Thank you, I am glad you like it, as far as the ores go yeah that was quite a discrepancy. Thanks for checking the count for me, I have turned them all to stone and replaced them more carefully, actually it was pretty cool to do because I figured I should place some of them like as if they are sort of power ups in the pvp chambers underground so there is now actually a reason to go into them, I think i placed them way more accurately this time in terms of distribution and definitely more scarcely. I  do have one problem, I dont know how to do a pull request, I have made a .tar archive of the new map version I could send to someone on discord.

**Comment by HobbitPower** [comment]
> I agree, the current speed is way too fast. Walking around the map feels like flying. Otherwise, I really like the map. A lot of effort is definitely spent on it. The builds look good and I didn’t find any bugs. It would be nice to finally see this map added to the game. I don’t think the ores needs to be the exact same amount for each team, but I tried counting with World Edit and they seem to differ a lot. Team red has 200 diamond ores with 65 diamond blocks. Team blue only has 61 diamond ores and 13 diamond blocks. Team red has 65 mese ores and 97 mese blocks. While team blue has 71 mese ores and 20 mese blocks.

You can ignore the diamond blocks (at least for now) as you cannot get diamonds from them. You can get mese crystals from mese blocks though. 

(Also just for the record, I will update the current PR once I got the correct files)

**Comment by src4026** [comment]
I tested the current map (as it is in its current state), and found no issues in the design and other factors. It's a solid map, I have to say! I do, however, I agree with the other reviewers that the speed is too fast. It's like the Flash when sprinting and jumping with the right blocks. For now, I shall wait till the ores are in balance. ~~Lol, there's a lot. Are they mostly from the caves/ground?~~. I am eagerly anticipating this map's merge to the repo after it has been refined furthermore. Amazing craftsmanship!

**Comment by omikekimo** [comment]
Thank you for your kind words, I am glad you like it, I have every reason to hope that hobbitpower has a version with the speed and ore situation under control. I say hope because I cant be sure yet, I thought that was the case yesterday but somehow some it got corrupted to an old version and on my computer was throwing errors after I saved it. Everything went weird, I have had a nightmare trying to figure out and fix it but i think i managed to sort it, so with any luck there will be an amended version being uploaded tomorrow.

**Comment by HobbitPower** [comment]
@omikekimo  speed  and ores were adjusted, however ores are still not equal:
image
The amount of mese blocks should definitely be the same for both sides. So please add some more for team blue, same for the normal diamond ores. diamond blocks are kind of useless, since you cant get diamonds out of them. You could remove the 6 diamond blocks imo.

**Comment by src4026** [comment]
#### Ores
Team Red:
- 3 `default:mese`
- 11 `default:stone_with_mese`
- 28 `default:stone_with_diamond`

Team Blue:
- 3 `default:mese`
- 10 `default:stone_with_mese`
- 23 `default:stone_with_diamond`

They seem fairly balanced. Though I would like your thoughts on the tiny disparity. 

#### Speed and other stuff
The speed is good now. IMO not too high nor too low. The reduced speed I feel is complimented by the 0.1 decrease in gravity and 0.1 increase in jump height.

**Comment by farooqkz** [comment]
I suggest adding diamond blocks equal to for both teams, like 30-40 diamond blocks per team. They can be used for building base and can add diversity to the game play. I further recommend having equal number of diamond blocks per team.

I also further recommend taking the damage diamond sword causes into consideration. Diamond swords to a bit more damage than mese swords. Thus, I would say 22 mese crystals equal to 20 diamonds.

**Comment by omikekimo** [comment]
The diamond blocks were removed completely, maybe I will add some in future but they were randomly distributed with the ores in this instance but as they cannot be mined and used for gaining diamonds I decded it would be easier to use worldedit to turn them to stone and redo the ores. Bear in mind they were present when the default loadout contained a shotgun but I do like your idea of having them available as a strong building material. I will think about how I could utilise them in this way perhaps in this map but more likely a future one. That may be a little while away though, I intend to learn how to be a map tester and help the team review and test some of the other new maps coming along because I have seen some excellent work shown on discord. Right now the version that hobbitpower uploaded yesterday is completely balanced in terms of ores and finished.

**Comment by src4026** [comment]
Looks good now :+1:

**Comment by omikekimo** [comment]
Thank you so much, I am glad you like it. I must admit part of me wants the tunnels to be undiscovered for a little while but i think they will find them straight away in all honesty. I hope the players enjoy it, I am looking forward to roof jumping with knockback nades and sprinting along the cables but I am sure other tactics are available.

**Review by MoreKat — COMMENTED** [review]
I honestly find the ores very hard to find. I checked, you put 9 mese blocks, 28 diamonds and 10-11 mese ores on each side. I was only able to locate a couple of those, using noclip and fly (I will admit that I'm bad at finding these things). I also think red has an advantage when it comes to the ore distribution because of one easily accessible spot where you've put 5 mese blocks (in the vault underneath the bank (?)). That's enough mese to make 22 swords, sufficient to provide every red team member with a sword. Maybe there is such a spot on blue side as well but I haven't found it.
So I want you to take a look at this before I approve.

**Comment by omikekimo** [comment]
There is a similar spot on the blue side, in the building with the peaked roof. they are up in the loft.

**Comment by MoreKat** [comment]
> There is a similar spot on the blue side, in the building with the peaked roof. they are up in the loft. They are visible through the loft window from the rooftops and you can get to that window across a cable or by stairs inside.
> 
> Also, i am really glad that it was recognizable as a bank.

Oh that's great. I think it's good to go then :)

**Review by HobbitPower — COMMENTED** [review]
Since I cannot approve my own PR's I use the comment function: I approve the map 🎉

**Pull request merged**
