### PR TITLE
Fix missing barriers underwater and holes in red barrier

### PR DESCRIPTION
**Pull request by JostP**
Closes: #71 

Maps affected by this bug (all rubenwardy's): 
* Two hills and two lakes
* Bridge
* Plains of the past
* Coast of nostalgia

I fixed red barrier underwater and replaced `ctf_map:ind_stone` with `ctf_map:stone` because MT world does not load `ctf_map:ind_stone` when you do //mtschemplace.

### CODE REVIEW

**Comment by JostP** [comment]
Done
Fixed:
- red barrier underwater and 
- replaced `ctf_map:ind_stone` with `ctf_map:stone` because MT world does not load `ctf_map:ind_stone` when you do `//mtschemplace`.

Tested, everything looks good. Ready for review

**Comment by Thomas--S** [comment]
> replaced ctf_map:ind_stone with ctf_map:stone

I'm not sure if this is a good idea. Afaik, we decided that ind_stone is the better option in some/many cases.

**Comment by ClobberXD** [comment]
@Thomas--S `ctf_map:ind_stone` is now just an alias of `ctf_map:stone`. I think you have something else in mind.

**Comment by Thomas--S** [comment]
I thought about the red barrier stone, but that's probably a different node.

**Comment by MinetestSam** [comment]
Found two holes in Plains Of The Past barrier
screenshot_20191205_130928
screenshot_20191205_130954
Also I'm pretty sure there holes on Ice Age too due to the snow and also below the middle due to water

**Comment by JostP** [comment]
Thomas--S I didn't replace any red barrier stone.

MinetestSam this holes happened because when map was created there was grass. So when CTF starts it replace grass with air and hole appear.
But if neccessary I can of course fix this holes.

**Comment by JostP** [comment]
I will check for IceAge if it needs fixing

**Comment by ClobberXD** [comment]
@JostP Feel free to fix the cheese holes in another PR. If you even want to plug those holes, ofc...

**Comment by JostP** [comment]
Holes looks quite ugly on some maps, so will add holes fix in this PR. I went through all maps:
- IceAge needs fixing red barrier underwater and holes
- Forest map needs fixing holes
- POTP needs fixing holes
- Towers needs fixing holes

WIP, I will finish PR probably after weekend.

**Comment by JostP** [comment]
Done.
Ready for review

**Comment by MinetestSam** [comment]
Semi-approval, only one map (Karsthafen Town) is left which needs its barriers fixed.
screenshot_20191207_160216
screenshot_20191207_160244

**Comment by JostP** [comment]
Will fix this one too, thanks for your thorough review MinetestSam :)

**Comment by JostP** [comment]
Done, fixed holes in barrier on karsthafen town map.

**Pull request merged**
