### PR TITLE
Iceage chests increase

### PR DESCRIPTION
**Pull request by LuismiInTheZone**
https://discord.com/channels/447819017391046687/448136308108296213/1127268509987115109 I think changing it to 50 is ok for now

### CODE REVIEW

**Comment by LuismiInTheZone** [comment]
Gonna make a last check to see how appears

**Comment by HobbitPower** [comment]
> Gonna make a last check to see how appears

Do you want to make any more changes?

**Comment by LuismiInTheZone** [comment]
> > Gonna make a last check to see how appears
> 
> Do you want to make any more changes to the amount?

No, seems good to me, do you think some more chests should be added?

**Comment by HobbitPower** [comment]
> > > Gonna make a last check to see how appears
> > 
> > 
> > Do you want to make any more changes to the amount?
> 
> No, seems good to me, do you think some more chests should be added?

I say 54 would working, too. Just let me know.

**Review by HobbitPower — APPROVED** [review]

**Pull request merged**
