### PR TITLE
repair plain battle

### PR DESCRIPTION
**Pull request by JostP**
Red side has only 4 mese (it should have 6). I have no idea how this happened :). So I added new 2 mese on red side.

****

Successor of #42

### CODE REVIEW

**Comment by ClobberXD** [comment]
The file name seems to be incorrect.

**Comment by JostP** [comment]
> The file name seems to be incorrect.

incorrect?

**Comment by ClobberXD** [comment]
It seems to be fine now o_O

I could've sworn it was `plain_battle.mts_10` before...

**Comment by Thomas--S** [comment]
Labeling as WIP (see #50)

**Comment by JostP** [comment]
Improved wall, different design. I made front row indestructible, other 5 are destructible so players can modify wall (behind indestructible row) as they want.

"Defence corridor" is still quite useless, because guns that we have aren't very useful for repeling enemies when they are moving. I hope "sniper mod" will make it more useful.

I also added shooter:pistol as spawn item to encourage players to use it.

PR is ready for review, and don't forget this PR was created to add 2 mese on red side.

And one screenshot:
Zaslonska slika 2019-09-20 17-23-11

**Comment by MinetestSam** [comment]
Checked mese on both the sides and yes indeed there are 6 on both the sides but my only concern with my map right now is that although the front row is indestructible the top of the towers are still destructible which either way I am fine with but I think it should be made indestructible
screenshot_20190921_155336

**Comment by JostP** [comment]
> Checked mese on both the sides and yes indeed there are 6 on both the sides but my only concern with the map right now is that although the front row is indestructible the top of the towers are still destructible which either way I am fine with but I think it should be made indestructible

indestructible wall is intended to prevent the invasion of enemys into "defence corridor", so I don't see why tower should be indestructible.

**Comment by MinetestSam** [comment]
See https://github.com/MT-CTF/maps/issues/50#issuecomment-532352895

**Comment by JostP** [comment]
Well, I will make towers indestructible, no problem, but I still think this isn't so neccessary.

**Comment by JostP** [comment]
Towers are now indestructible

**Comment by MinetestSam** [comment]
The `.conf `file seems to be missing the license.

**Comment by JostP** [comment]
Added license

**Comment by JostP** [comment]
License was actually already added for this map in #49, but I created this PR before adding a license.

**Pull request merged**
