### PR TITLE
Map To Review: Hill CTF by Darkf4antom and SoulSeeker

### PR DESCRIPTION
**Pull request by moreavy**

### CODE REVIEW

**Comment by moreavy** [comment]
I tested, here are my thoughts:

- Your map is too plain leaving the ugly hill in the middle
- The hill in the middle is not looking like a hill
- Nothing too much unique
- The ugly and broken construction surrounding the base will make it difficult to build reinforcements outside the base. I know players can make larges reinforcements but that will take more resources to build it.

image

**Comment by Alone0ne** [comment]
WIP

**Comment by RyanZem** [comment]
This map is too flat and I can't dig anything only stone.
Make this map more interesting and I can see beyond the glass barrier other dirt, replace it on the dirt what you made the map.

**Comment by moreavy** [comment]
> This map is too flat and I can't dig anything only stone.
> Make this map more interesting and I can see beyond the glass barrier other dirt, replace it on the dirt what you made the map.

You should wait to test WIP maps.

**Comment by Realyg-Hmar** [comment]
Can't say anything im totally agree with moreavy .

**Pull request closed without merging**
