### PR TITLE
Add "The ice age zone" map by Waterbug

### PR DESCRIPTION
**Pull request by JostP**
https://forum.minetest.net/viewtopic.php?f=12&t=19729&start=175#p363745

### CODE REVIEW

**Comment by JostP** [comment]
Marking as `Action/change need` because screenshot have to be added.

**Comment by JostP** [comment]
Screenshot added. Ready for review.

**Comment by MinetestSam** [comment]
Map is very empty and I have mixed opinions regarding the map.

**Comment by ClobberXD** [comment]
Map looks a wee bit uninteresting, and somewhat resembles existing maps. :-1: at the moment.

**Comment by JostP** [comment]
Reviewed
very plain; we already have to many plain maps so map gets won't add label.
Zaslonska slika 2020-07-14 13-51-08

**Pull request closed without merging**
