### PR TITLE
Add Cave Wars by Waterbug

### PR DESCRIPTION
**Pull request by ClobberXD**
Originally on https://forum.minetest.net/viewtopic.php?p=357138#p357138

[screenshot](https://forum.minetest.net/viewtopic.php?p=357166#p357166)

#### TODO

- Currently missing a license.
- Map is 200m tall, without a strong reason, AFAIK.

### CODE REVIEW

**Comment by ClobberXD** [comment]
Added the aforementioned image as screenshot.

**Comment by Enrikoo** [comment]
`2019-09-20 15:59:09: ERROR[Main]: ModError: Failed to load and run script from C:\Users\User\Downloads\minetest-5.1.0-dev-win64\minetest-5.1.0-dev-win64\bin\..\games\capturetheflag\mods\ctf\ctf_map\init.lua:
2019-09-20 15:59:09: ERROR[Main]: ...n\..\games\capturetheflag\mods\ctf\ctf_map/schem_map.lua:113: assertion failed!
2019-09-20 15:59:09: ERROR[Main]: stack traceback:
2019-09-20 15:59:09: ERROR[Main]: 	[C]: in function 'assert'
2019-09-20 15:59:09: ERROR[Main]: 	...n\..\games\capturetheflag\mods\ctf\ctf_map/schem_map.lua:113: in function 'load_map_meta'
2019-09-20 15:59:09: ERROR[Main]: 	...n\..\games\capturetheflag\mods\ctf\ctf_map/schem_map.lua:211: in function 'load_maps'
2019-09-20 15:59:09: ERROR[Main]: 	...n\..\games\capturetheflag\mods\ctf\ctf_map/schem_map.lua:225: in main chunk
2019-09-20 15:59:09: ERROR[Main]: 	[C]: in function 'dofile'
2019-09-20 15:59:09: ERROR[Main]: 	...64\bin\..\games\capturetheflag\mods\ctf\ctf_map\init.lua:23: in main chunk
2019-09-20 15:59:09: ERROR[Main]: Siehe debug.txt für Details.`
This happens when I try to load this map. Will be there a fix please?

**Comment by ClobberXD** [comment]
The map is not complete, as mentioned in the first post. I got the exact same error too, and this is apparently because of the size of the map - CTF is designed to crash if the map is larger than a certain size, how cool is that? :D

**Comment by JostP** [comment]
It happened the same when I tried to test the map yesterday, if I remember correctly

**Comment by MinetestSam** [comment]
Please update.https://forum.minetest.net/viewtopic.php?p=358379#p358379

**Comment by MinetestSam** [comment]
Closing as the map maker wants to redo the map completely. 
See: https://forum.minetest.net/viewtopic.php?f=12&p=360902#p360775

**Comment by ClobberXD** [comment]
I already did have doubts as to whether I'd have the time to maintain this PR. Thanks for letting me know.

**Pull request closed without merging**
