### PR TITLE
Add The Great Wall of China by -lipop-

### PR DESCRIPTION
**Pull request by moreavy**

### CODE REVIEW

**Comment by olliy1or** [comment]
missing screenshot and license

**Comment by moreavy** [comment]
@olliy1or added license and screenshot.

**Comment by Panquesito7** [comment]
@moreavy Did you ask -lipop- for permission to add the license?

**Comment by moreavy** [comment]
> @moreavy Did you ask -lipop- for permission to add the license?

Yes, I asked him to read the `map_maker`'s README.md and choose 1. He himself chose CC BY-SA 4.0

**Review by Panquesito7 — COMMENTED** [review]
From viewing the screenshot itself, the map looks kinda plain; we already got too many plain maps.

**Comment by moreavy** [comment]
> From viewing the screenshot itself, the map looks kinda plain; we already got too many plain maps.

-lipop- is adding more to it. He is adding lighthouses and other constructions

**Comment by RyanZem** [comment]
The wall looks nice but it's very similar to map "The Wall" and it's flat and yet I don't see any buildings in this map and the wall what you built. Add yet some buildings in this map and make it not very flat.

**Comment by moreavy** [comment]
> i think the china wall is too similar to the Thomas-S's wall so it will never be included in the game so you can end the discussion on github.

These are -lipop-'s words

**Pull request closed without merging**
