### PR TITLE
Add Monolithic Mountain by Camasia

### PR DESCRIPTION
**Pull request by BrianGaucher**
I have not finished, but it nearly is.

### CODE REVIEW

**Comment by BrianGaucher** [comment]
I still need to do a little bit of terraforming to facilitate navigation. As well as add some ores. Then remove some plannification nodes (signs & torches). Then a thorough review.

**Comment by BrianGaucher** [comment]
I still need to do a little bit of terraforming to facilitate navigation. As well as add some ores. Then remove some plannification nodes (signs & torches). Then a thorough review.

**Comment by BrianGaucher** [comment]
Maybe we should add the tag "Action/Change needed" since it's unfinished.

**Comment by ClobberXD** [comment]
Sorry, didn't notice that this map was unfinished. :)

**Comment by BrianGaucher** [comment]
I'm getting closer to finishing.
[X] Done removing caves that leave the map.
[ ]Half done adding ores (since the entire map is above sea-level, and severly lacked ores).
[X] Done adding an indestructible wall in the mountain between the flags (to prevent 2 minute rounds).
[ ] Still need to do some minor terraforming to facilitate climbing the mountain.

**Comment by BrianGaucher** [comment]
Alright, 99% done.
I'll test my schems now to verify everything works.

**Comment by BrianGaucher** [comment]
Tested, seems good. I only tested the schem though, I don't know how to test it as a server match.

This map is no longer a WIP. Could you remove this tag.

**Comment by ClobberXD** [comment]
You can test it like so:

- Download [capturetheflag](https://github.com/MT-CTF/capturetheflag) game into `<minetest>/games`
- Copy-paste the schem and conf into `<minetest>/games/capturetheflag/mods/ctf/ctf_map/maps`
- Create a new world for capturetheflag
- Launch the game
- Enter chat-commands `/set_next monolithic` (sets the next map to be the given one) and `/ctf_next` (skips to next map immediately) in the same order.

**Comment by BrianGaucher** [comment]
Thank you, I'll test when I can. Might be someday this week, I'll see how school goes.
I'll use this to review other maps too.

On February 24, 2019 7:56:09 PM EST, ANAND <notifications@github.com> wrote:
>You can test it like so:
>
>- Download [capturetheflag](https://github.com/MT-CTF/capturetheflag)
>game into `<minetest>/games`
>- Copy-paste the schem and conf into
>`<minetest>/games/capturetheflag/mods/ctf/ctf_map/maps`
>- Create a new world for capturetheflag
>- Launch the game
>- Enter chat-commands `/set_next monolithic` (sets the next map to be
>the given one) and `/ctf_next` (skips to next map immediately) in the
>same order.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MT-CTF/maps/pull/16#issuecomment-466837502

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by BrianGaucher** [comment]
I tested it out, I forgot to set the orientation during initial creation. Fixed that.
Only issue now is deciding what players begin with.
I think stone pick and stone sword would work well, but 3 torches would be nice. and maybe 5 ladders.

**Comment by BrianGaucher** [comment]
Schematic all good. Configuration complete. Tested as a server by myself. Initial stuff complete. Just needs to be tested and approved.

**Comment by JostP** [comment]
I tested your map, BrianGaucher.
I have 2 suggestions to improve your map.


Believe me, players always makes tunnels if possible. I saw your indestructible wall inside the mountain, but i don't think it is enough big. I made screenshot (indestructible wall is inside digged blocks):

Zaslonska slika 2019-03-09 09-48-54

I think you should make indestructible wall a lot higher, deeper and wider so tunneling will be impossible.

And second, "r" of your map is 50, so your map is 4 times smaller than average ctf map (r = 110). So on your map is only 1/4 chests and spawned chests are too less IMO. I suggest to make custom chest zones and make number of chests to be placed in the zone between 30 and 50.

**Comment by BrianGaucher** [comment]
@JostP Thanks for your review.

I'll be away all this week, but I'll implement your suggestion. I'll widen the wall. Question, should the wall span the entire height, or allow the very top section to be dug? (the top 20ish nodes).

Also only the top 40ish nodes are ore enriched, (coal is everywhere, steel also spawns below sea level) any comment on that.

Would the water around the map cause issues if it overflows?

**Comment by BrianGaucher** [comment]
@ClobberXD Could you add "Action/ Change needed".

**Comment by ClobberXD** [comment]
@BrianGaucher Let me repeat - `Action / change needed` is only for issues and PRs which are felt by the official reviewers to be incomplete. Other suggestions or work that you take upon yourself, classifies as `WIP`. Don't bother about these labels anyway, these are just for us reviewers to keep track of stuff, and don't indicate the reputation of the PR in any way.

**Comment by JostP** [comment]
> ... or allow the very top section to be dug? (the top 20ish nodes).

I think, this is good idea. It is hard to climb up on the top of the mountain.


> Would the water around the map cause issues if it overflows?

I think it doesn't.

**Comment by JostP** [comment]
Maybe ti would be good, if you build a base/fortress on the top of mountain and on left and right side of the map. They are useful for defence and make game more interesting. Only suggestion.

**Comment by BrianGaucher** [comment]
@ClobberXD Sorry, I'll stop worrying about labels. And just post a message when I feel it's complete.

**Comment by BrianGaucher** [comment]
I won't build any towers on it, they aren't necessary for the map. But I'll fix the border in the mountain. I'll also fix the water just in case it would cause issues.

I'll also add the whole map as a chest area to enrich it slightly. I'll also make the top of the hill a third chest region (to encourage people to climb). And finally add a couple of chest in the cave.

**Comment by BrianGaucher** [comment]
I have added the indestructible stone in the middle. Also, I used indestructible stone bricks so it's more obvious that it isn't normal bricks. I haven't added custom chest zones yet.

I am trying to figure out the best way to modify existing maps.

**Comment by ClobberXD** [comment]
@BrianGaucher What's left to address for this map to be merge-worthy? Are you still working on this?

**Comment by ClobberXD** [comment]
Closing due to lack of response from author. Can re-open upon progress.

**Pull request closed without merging**
