### PR TITLE
A Trench Map

### PR DESCRIPTION
**Pull request by hermassest**
requested from one of the players i played with in mt-ctf

### CODE REVIEW

**Comment by HobbitPower** [comment]
That's not how you create a map for CTF. You need to upload the map.mts file, the map.conf file and a screenshot. For instructions follow this link: https://github.com/MT-CTF/capturetheflag/tree/master/mods/ctf/ctf_map#ctf-map---map-maker
@hermassest

**Comment by LuismiInTheZone** [comment]
I don't know how you did this but you need to use the command /ctf_map e and when you put all the stuff, you put the .mts and .conf file

**Comment by hermassest** [comment]
But wats a map.mts and a map.conf

**Comment by hermassest** [comment]
And where do i writhe the command

**Comment by HobbitPower** [comment]
Please read the instructions how to make a map for CTF @hermassest You need to install the CTF subgame from the ContentDB of Minetest. Looks like you have created a map in a normal Minetest map. 
Please read the instructions (https://github.com/MT-CTF/capturetheflag/tree/master/mods/ctf/ctf_map#ctf-map---map-maker) if you want to contribute a map for CTF.

**Pull request closed without merging**
