### PR TITLE
Remove karsthafen bridge map

### PR DESCRIPTION
**Pull request by JostP**
Closes issue #93 and #84 

EDIT:
Changes in this PR:

- remove karsthafen bridge
- rename karsthafen town to karsthafen
- re-add doors ( #84 )
- improve blue base's position
- new screenshot
- 50 chests on each side instead of 70

### CODE REVIEW

**Comment by ClobberXD** [comment]
I think bridge has buildings in a more distributed fashion, while town has fewer buildings clumped together in the middle. The screenshots seem to confirm that as well. Also, the blue base in town map is at a big strategis disadvantage due to the various access points around, compared to the more guarded red base. Given these points, I'm more inclined to see the town map being removed.

@JostP, if you're not satisfied with bridge, we could replace it with another map of Karsthafen, this time with a lot of buildings.

**Comment by samuelstegerKOLLEGAH** [comment]
Yes i think its better to remove it.

**Comment by JostP** [comment]
Rebased.
I tested both maps again and I insist on removing karsthafen bridge. I noticed problem on it that there is something like only one way (one main street which leads from first to second base). Contrary karsthafen town has more branched streets and consequently more ways that leads to enemy base. Also it is more sniper friendly.

> Also, the blue base in town map is at a big strategis disadvantage due to the various access points around, compared to the more guarded red base.

Yes this is true and I am going to move blue base a little.

**Comment by JostP** [comment]
Finished:
Changes in this PR:

- remove karsthafen bridge
- rename `karsthafen town` to `karsthafen`
- re-add doors ( #84 )
- improve blue base's position
- new screenshot
- 50 chests on each side instead of 70

**Comment by JostP** [comment]
Tested works, merging...

**Pull request merged**
