### PR TITLE
Changes to Mini Village map

### PR DESCRIPTION
**Pull request by AnyBlue**
Added mese and diamonds + mine, removed some houses, made the glass in village houses breakable, added bronze sphere, added hint, fixed chairs in a base house. I don't really remember what we added yet but I think it's everything what we made.

### CODE REVIEW

**Comment by JostP** [comment]
`This branch has conflicts that must be resolved`
I think you should fork maps repository again, because this one has some conflicts. You can also try to rebase, but it is not easy.

**Comment by AnyBlue** [comment]
> `This branch has conflicts that must be resolved`
> I think you should fork maps repository again, because this one has some conflicts. You can also try to rebase, but it is not easy.

What conflicts? :(

**Comment by JostP** [comment]
Zaslonska slika 2020-12-14 09-16-51

**Comment by AnyBlue** [comment]
And how can I resolve it?

**Comment by JostP** [comment]
> And how can I resolve it?

I am not sure, you can try to find a solution on the internet

**Comment by AnyBlue** [comment]
Can I make another branch?

**Comment by JostP** [comment]
> Can I make another branch?

You should first update, rebase your master with MT-CTF/maps

**Comment by AnyBlue** [comment]
> > Can I make another branch?
> 
> You should first update, rebase your master branch with MT-CTF/maps

I can fork again

**Comment by JostP** [comment]
> > > Can I make another branch?
> > 
> > 
> > You should first update, rebase your master branch with MT-CTF/maps
> 
> I can fork again

good idea

**Pull request closed without merging**
