### PR TITLE
Add "mayan_legend"

### PR DESCRIPTION
**Pull request by ClobberXD**
(This pull request was generated by a script)

### CODE REVIEW

**Comment by olliy1or** [comment]
1  map is unique
2  map is playable
3 feel like its would be enjoyable looks fun to play on idk about others
4  no broken barriers players can get out of

**Comment by Zipitque** [comment]
Still wondering how to play it in single player anyhelp?

**Comment by JostP** [comment]
> Still wondering how to play it in single player anyhelp?

@Zipitque 
Clone ClobberXD's maps repository. Place it in capturetheflag/mods/ctf/ctf_map/ctf_map_core/maps

**Comment by JostP** [comment]
Reviewed.
Maps works perfectly. There are some things that needs to be fixed:

1. There are some random caves. Inside them you can see appearing chests. There is always 23 chests on one side of the map, so if chests appear in caves, players get fewer chests. I suggest you to fill caves with stone or something. From what I have seen, there is no need for chest zones.

Zaslonska slika 2020-07-14 16-57-09

2. There is something like tunnel on the top of the map, which appear when red barrier disappear. It is not important to fix this, but it would be better as maps mustn't have random holes.
Zaslonska slika 2020-07-14 16-58-37


When you fix this I will do a final review and your map will get it's first approval.

**Comment by JostP** [comment]
Closing as author is not available anymore...

See #102 for PR v2

**Pull request closed without merging**
