### PR TITLE
Add Snow and Lava map by realyg

### PR DESCRIPTION
**Pull request by AnyBlue**
A map made by realyg, Amine35

### CODE REVIEW

**Comment by winniepee** [comment]
Seems okay, no bugs found.

**Comment by Avyukt1** [comment]
Can you name the map like
`Snow vs Lava
or
`Water vs Lava`
?

**Comment by olliy1or** [comment]
The map is a bit like lava puddles map
gives a big advantage to reds because the whole snow side is made out of snow and snow can be easily broken by guns

**Comment by JostP** [comment]
I agree with olliy.
- very plain
- there are already maps like this on server
- something quickly WorldEdited

I also asked discord community and they agree too.

**Pull request closed without merging**
