### PR TITLE
Add "Burning sands map" by Waterbug

### PR DESCRIPTION
**Pull request by JostP**
https://forum.minetest.net/viewtopic.php?f=12&t=19729&start=175#p363745

### CODE REVIEW

**Comment by JostP** [comment]
Marking as `action/change needed` because screenshot is missing.

**Comment by JostP** [comment]
Screenshot added. Ready for review.

**Comment by MinetestSam** [comment]
Map is very empty and I have mixed opinions regarding the map.

**Comment by samuelstegerKOLLEGAH** [comment]
The barriers and everything else work very fine but, a bit boring tho... and looks a bit like the boring old sand map which was removed ...

**Comment by JostP** [comment]
Some buildings (a small towers somewhere or small cowboy village...)  and cactuses should be added, then I will approve this map.

**Comment by samuelstegerKOLLEGAH** [comment]
Cowboy Villages are a very good Idea

**Comment by MinetestSam** [comment]
> Some buildings (a small towers somewhere or small cowboy village...) and cactuses should be added, then I will approve this map.

I don't like buildings in maps and feel like this map is rather better to be left plain.

**Comment by JostP** [comment]
So MinetestSam do you think this map is good enough to be added? I remember there was a discussion on discord about this and most people wanted it to be added.

Btw, you have probably heard that ANAND had left minetest permanently?

**Review by JostP — COMMENTED** [review]
Looks good

**Pull request merged**
