### PR TITLE
This is my PR.....

### PR DESCRIPTION
**Pull request by KodaTheGuy**

### CODE REVIEW

**Comment by samuelstegerKOLLEGAH** [comment]
Map doesnt load completely for me just the base and this bugs the whole time. 
Could u maybe send me a zip file of the map ?

**Comment by Zipitque** [comment]
How do you play it?

**Comment by JostP** [comment]
Map doesn't work, try to fix it and test in CTF game as singleplayer.

**Comment by samuelstegerKOLLEGAH** [comment]
From what I see there are broken barrriers, not all nodes are working, the map is really plane and really boring... It hasnt to do anything with twillight or vampires or whatever...

**Comment by JostP** [comment]
This map is too much plain... We already have too many plain kind of maps in CTF. Don't ask how many plain maps we have rejected... I don't even remember all of them :thinking:

**Comment by MinetestSam** [comment]
The map is broken and quite flat to be honest. Seems like you have placed the barrier nodes manually. Closing.

**Pull request closed without merging**
