### PR TITLE
Add Big Ocean by gameit

### PR DESCRIPTION
**Pull request by MinetestSam**
https://forum.minetest.net/viewtopic.php?p=350983#p350983

### CODE REVIEW

**Comment by JostP** [comment]
I think stone under map should be removed or replaced with water because players can freely make tunnels and map lose its point.

 Zaslonska slika 2019-07-08 10-32-21

Why steel pick? There is only a little stone on surface.

**Comment by MinetestSam** [comment]
I think it would be better to write the review on the forum page since the user is not on github

**Comment by MinetestSam** [comment]
gameit's response to -sniper-

```
I can remove the stone, but the steel pick-axe isn't important that way.

Under a real ocean are much things like coal and iron. If I make ores in the stone too, the map would be more realistic and you can use the steel pick-axe to mine.

What is the better way??
```

**Comment by MinetestSam** [comment]
I won't be able to regularly update this PR, so I would like someone else to open this PR (I am really sorry).

**Comment by ClobberXD** [comment]
PR needs adoption. Re-opening for attention.

**Comment by JostP** [comment]
continue #48

**Pull request closed without merging**
