### PR TITLE
Add "Race Day" by sonicSMASH and tailsSMASH

### PR DESCRIPTION
**Pull request by sonicSMASH**

### CODE REVIEW

**Comment by LuismiInTheZone** [comment]
I can't enter in the map... It haves something that kicks me from the game, I can't enter into the minetest worlds if I have in the ctf folder your map, I don't know if that happens to the rest of people but I tried with other maps and the game let me enter into minetest worlds.

**Comment by LuismiInTheZone** [comment]
It's seems everything is ok... only problem is there isn't a floor so I can just dig down and and see the emptiness. Great job with the map, it's very cool.

**Comment by MoreKat** [comment]
This isn't my full/final review but one thing that you should definitely fix are the unbreakable base floors. The stone blocks can be dug. Also, you have these giant empty spaces/rooms underneath the build, are those supposed to be accessible? Some of them are, some aren't.

**Comment by HobbitPower** [comment]
Also take a look at the team zones. You get teleported back during building time, while standing at the red barriers. At least for every team except green it seems.

**Comment by sonicSMASH** [comment]
The stone road is supposed to be breakable, if that's what you mean. I found out about the barriers, will fix that soon.

**Comment by MoreKat** [comment]
> The stone road is supposed to be breakable, if that's what you mean. I found out about the barriers, will fix that soon. Does it need a barrier at the bottom??

Yes it needs a barrier at the bottom. I don't mean the stone roads, I mean the stone blocks you used to build the floor under the flag.
The problem with the empty, inaccessible rooms is that they still contain chests so it's probably better to fill them in.

**Comment by sonicSMASH** [comment]
So default:stone_block?

**Comment by LuismiInTheZone** [comment]
I tested again and: 

- It seems to be fine, but there are many rooms I can't enter, I don't know what your plan is, but I can enter like one room per base...
- Also the orange team has 2 mines, I don't know if you check it but... I think it's a bit unfair... Maybe I'm wrong and I didn't look well and each team has got two mines... but it doesn't seem like that.

**Comment by ColorBlob** [comment]
I'm not done testing the map yet, but I did find a giant empty space/room near orange's base IIRC, and chests are spawning in it. That might need to be filled up.
Also, part of the barrier isn't loaded in the screenshot, so part of the wall and barrier glass are missing. But I don't think that's a serious issue.

**Review by MoreKat — COMMENTED** [review]
Team zones still seem off. You get teleported back when you try to climb the ladders in the base so they seem to be one block too narrow (please check this for yourself). Also I'm afraid that, with the bases being fully unbreakable, it's way too hard to get the flag. The existing exits can easily be closed off so it will be very hard for the enemy to make it in and out. Maybe you can make the roof partly breakable or add more exits or something else.
Also you should add a better pickaxe to initial stuff, there's a lot to dig. I also suggest adding torches.
Finally, I suggest adding more lights to the giant hallways and filling in the random empty rooms.

**Comment by sonicSMASH** [comment]
> Also you should add a better pickaxe to initial stuff, there's a lot to dig. I also suggest adding torches. 

There are iron ores to mine, cant't players make pick that way?

**Comment by sonicSMASH** [comment]
After your comments, here's what I (and tails) did:

- Block up spaces that aren't accessible (or most of them)
- Add a new stairway on opposite sides of map
- make walls on opposite sides _glass_
- Make floors **diggable**
- Fix barrier teleport
If there's something else, let me know please.

**Comment by ColorBlob** [comment]
Glad to see most of the empty spaces filled up. But, I still see a few empty spaces near the mines, especially near team orange's mine.
Also, the game still teleports you back when climbing the ladder, at least for team blue, so the team zones are still off by one block. 
This is a personal opinion, but I think you should light up the tunnels and hallways better, it's hard to see. Or, at least give players more torches to place.

**Comment by LuismiInTheZone** [comment]
The test: I just started and I can't climb the stairs of the base, it says that I can't cross the barrier early

**Comment by ColorBlob** [comment]
Also, the ores on each team's sides are extremely unbalanced. Teams such as blue and green have more diamond ores than the rest. It's recommended to keep the ores balanced to make it a fair game for everyone.

**Comment by sonicSMASH** [comment]
Added some rooms, made another tunnel, etc.
It should not teleport you when going up ladder, you must have had noclip on

**Comment by MoreKat** [comment]
First of all: why is game_modes empty? Should not be the case. Second, only team blue's team zone seems correct. In purple it's one block off on west side, in orange on south side and in green on north side. That's why you get teleported back to the base when you try to climb the ladder, it's located in that area. The bases are still not accessible enough. I recommend making the roof breakable.

**Comment by sonicSMASH** [comment]
I don't know why game modes are empty, didnt change that.

**Comment by HobbitPower** [comment]
> Ok guys, here are some changes:
> 
> * Roof breakable now


* The roofs are still not breakable. Thats only the case for team green, blue only got a tiny hole. 
* You could lower the glass ceiling imo. There is no need for such lost space. The helicopter could be the highest point of the map. Remember you then have to update the corners of the map + team zones + the red barrier + barrier area aswell
* I'm following Kat's request to add a better a pickaxe as an initial item

**Comment by HobbitPower** [comment]
_(From Discord):_

> @HobbitPower sorry 4 ping but I did what u suggested in github except for changing maps height
* By that you mean you have changed the roofs. More or less. I don't know why there are random blocks like obsidian or unbreakable meselamps in the layers between base roof and the tunnel above, but okay. At least you can now enter every base from the tunnel above. FYI: you have placed a stonebrick instead of a silver sandstone. I think that happened by accident, I don't know if you want to keep it that way. 
* I don't get the changes you have made in the conf file. It seems like now (or maybe that was also the case before) the team zones are again broken: When I play as blue I can dig under the red barrier (facing the orange team). I can enter oranges team zone and walk there like 4 blocks wide. So please check ALL teamzones again. You are not supposed to be able to cross any barrier. I recommend that you test your map before updating it here again. (If you don't know how to test it, you can send me a PM at Discord)
* You still have a stone pick as an initial item. For example you can't dig mese with a stone pick. Is there a reason you don't want to upgrade it? 
* One red barrier goes into the unbreakable glass ceiling now. You can simply just change the top layer to the unbreakable barrier glass.

**Comment by LuismiInTheZone** [comment]
@sonicSMASH You still haven't done what we said about covering places where you can't get to loot them, so pls, cover them so chests can't appear... Also you haven't filled the floor of the map, I still see parts without been filled...
Minetest 5 6 0  Singleplayer   OpenGL 4 6 0  16_02_2023 19_21_16

**Comment by ColorBlob** [comment]
- Why is the bottom barrier glass? Wouldn't it be better to make the bottom barrier indestructible stone?
- You placed a two-node-thick line of red barrier glass at the bottom of the map. After build-time ends, it will disappear and turn into what Luis is demonstrating above ^^^.
- If you dig straight down during build-time on team Green, Purple, and Orange, you get teleported back to base. However, this problem doesn't apply to team Blue. 
- ALSO why is the red glass barrier 2-to-3 nodes thick? One-node-thick is enough.
- Again, the ores for each team are very unbalanced. Recourses for each team need to be about the same.

**Comment by sonicSMASH** [comment]
The barrier has to be thick because the even number of blocks between the wall and the middle of the map would allow only one team to enter the doors

**Comment by sonicSMASH** [comment]
I have done the following:

- Make the barrier 2 blocks thick instead of 3.
- Deleted the red glass at bottom.
- Set floor to ctf_map:stonebrick
- **Copy and paste ores across teams**
- Make map look a little less like it was built by a 5-year-old.

**Comment by LuismiInTheZone** [comment]
I'm sorry to say this but your only fixed the 10% of the errors: the floor

Look:

- Please don't leave gaps around the bases, chests can spawn there!!!
Minetest 5 6 0  Main Menu  12_03_2023 10_12_35

- A part from the red barrier is missing... where's that?
Minetest 5 6 0  Multiplayer   OpenGL 4 6 0  12_03_2023 10_19_52

- Ores are the last thing that are the same:

team blue: 38 mese and 28 diamonds
team green: 32 mese and 25 diamonds
team purple: 13 mese and 13 diamonds
team orange: 16 mese and 17 diamonds

**Comment by sonicSMASH** [comment]
How are you counting the ores ?

> I'm sorry to say this but your only fixed the 10% of the errors: the floor
> 
> Look:
> 
> * Please don't leave gaps around the bases, chests can spawn there!!!
>   Minetest 5 6 0  Main Menu  12_03_2023 10_12_35
> * A part from the red barrier is missing... where's that?
>   Minetest 5 6 0  Multiplayer   OpenGL 4 6 0  12_03_2023 10_19_52
> * Ores are the last thing that are the same:
> 
> team blue: 38 mese and 28 diamonds team green: 32 mese and 25 diamonds team purple: 13 mese and 13 diamonds team orange: 16 mese and 17 diamonds

**Comment by LuismiInTheZone** [comment]
You just fixed the barrier problem, other two problems are at there

**Comment by a-blob** [comment]
To answer your question, ores are counted using world edit.

**Comment by LuismiInTheZone** [comment]
> To answer your question, ores are counted using world edit.

And I'm using world edit and ores aren't exact

**Comment by LuismiInTheZone** [comment]
> You just fixed the barrier problem, other two problems are at there

SonicSmash, you asked me if I saw the changes. There are not any updates, if you mean from the other day you need to fix ores and gaps

**Comment by LuismiInTheZone** [comment]
Nice everything is ok except the ores!!! Pls fix the ores!!!!

**Comment by LuismiInTheZone** [comment]
> Nice everything is ok except the ores!!! Pls fix the ores!!!!


https://user-images.githubusercontent.com/83732589/227717517-318811c0-8108-438c-a92f-385d51c0e2ee.mov

**Comment by sonicSMASH** [comment]
I'm not sure what i'm seeing in the video, but i will look into it. Could you tell me how you use worldedit to count stuff? (please)

**Comment by a-blob** [comment]
Ores are balanced, and I did not find any issues, except for team green.

- I still get teleported back to base when I dig down on team green. So green's team zone seems to be a bit off.
- Also, green seems to have twice the amount of ores compared to the other teams. That is probably caused by this _unidentified flying object_:
image

**Comment by LuismiInTheZone** [comment]
My work here is done, you made a great job, now you need to HobbitPower and Kat to approve the map

**Comment by LuismiInTheZone** [comment]
This afternoon (for me), if nobody checked it to the moment, I'll check how's the map, so... in around 12 hours since now

**Review by MoreKat — COMMENTED** [review]
It looks great, amazing job. Only thing I would change is increasing the phys_speed to 1.5 (it's quite a large map so players have to travel long distances). Once that's done I'll approve.

**Comment by HobbitPower** [comment]
Very nice looking map, that also offers different tactics thanks to the different entrances. Everything working fine. I approve.

**Pull request merged**
