### PR TITLE
Add "A Kingdom In The Nether" map by Waterbug

### PR DESCRIPTION
**Pull request by JostP**
continuation of #54

### CODE REVIEW

**Comment by JostP** [comment]
This map doesn't have `ctf_map:stone` barrier, should it has it?

**Comment by MinetestSam** [comment]
Yes, the maps should have `ctf_map:stone` as barriers for consistency with other maps.

**Comment by JostP** [comment]
Labeling as `Action/change needed` because, change need following:

- [ ] Make barriers with `ctf_map:stone` (exterior nodes)
- [ ] \(Optional) Add custom chest zones

**Comment by MinetestSam** [comment]
The screenshot of the map could be improved because currently it doesn't show much and the barriers need to be changed to ctf_map:stone. Rest everything looks fine.

**Comment by JostP** [comment]
New screenshot as original from previous PR wasn't very good.

**Comment by JostP** [comment]
Update
Ready for review

Tested LGTM :+1: 
One more approval needed by ANAND or Thomas--S.

**Comment by ClobberXD** [comment]
PR needs to comply with the new directory structure.

**Comment by KaylebJay** [comment]
:tada: Yay!

**Pull request merged**
