### PR TITLE
adding simple_village map

### PR DESCRIPTION
**Pull request by farooqkz**
This is a simple village map without almost any modification. Generated using https://content.minetest.net/packages/Nore/mg/

This is my first map please don't kill me :))

### CODE REVIEW

**Comment by RyanZem** [comment]
screenshot
CTF doesn't support farming and bed mods.

I don't think others will like the map because of the forest. Forest maps are boring. I think it will be a bit difficult to capture also.

**Comment by farooqkz** [comment]
@RyanZem those are for decoration. Any way to keep them?
And this map meant to be a village map.

**Comment by RyanZem** [comment]
> @RyanZem those are for decoration. Any way to keep them? And this map meant to be a village map.

CTF doesn't support beds and farming mods.

**Comment by farooqkz** [comment]
okay I'll try removing them

**Comment by farooqkz** [comment]
Hey do I need to rebuild the map for v3?

**Pull request closed without merging**
