### PR TITLE
New map: Desert City

### PR DESCRIPTION
**Pull request by Emojigit**

### CODE REVIEW

**Comment by JostP** [comment]
This part has already been suggested to be added but there were problems. See comments:

https://github.com/MT-CTF/maps/pull/15#issuecomment-460419886
https://github.com/MT-CTF/maps/pull/22#issuecomment-462146770
https://github.com/MT-CTF/maps/pull/15#issuecomment-461739360
https://github.com/MT-CTF/maps/pull/22#issuecomment-462147974

Thanks for your efforts to make good maps.

**Comment by Emojigit** [comment]
> This part has already been suggested to be added but there were problems. See comments:
> 
> [#15 (comment)](https://github.com/MT-CTF/maps/pull/15#issuecomment-460419886)
> [#22 (comment)](https://github.com/MT-CTF/maps/pull/22#issuecomment-462146770)
> [#15 (comment)](https://github.com/MT-CTF/maps/pull/15#issuecomment-461739360)
> [#22 (comment)](https://github.com/MT-CTF/maps/pull/22#issuecomment-462147974)
> 
> Thanks for your efforts to make good maps.
> 
> EDIT: Personally, I have nothing against churches (or mosques), but I agree with ANAND and Thomas--S that they aren't really suitable for being in-game. The players who play CTF are from whole world and are members of different cultures/religions.

[#15 (comment)](https://github.com/MT-CTF/maps/pull/15#issuecomment-460419886) : where is the church on this map?

**Comment by JostP** [comment]
> > This part has already been suggested to be added but there were problems. See comments:
> > [#15 (comment)](https://github.com/MT-CTF/maps/pull/15#issuecomment-460419886)
> > [#22 (comment)](https://github.com/MT-CTF/maps/pull/22#issuecomment-462146770)
> > [#15 (comment)](https://github.com/MT-CTF/maps/pull/15#issuecomment-461739360)
> > [#22 (comment)](https://github.com/MT-CTF/maps/pull/22#issuecomment-462147974)
> > Thanks for your efforts to make good maps.
> > EDIT: Personally, I have nothing against churches (or mosques), but I agree with ANAND and Thomas--S that they aren't really suitable for being in-game. The players who play CTF are from whole world and are members of different cultures/religions.
> 
> [#15 (comment)](https://github.com/MT-CTF/maps/pull/15#issuecomment-460419886) : where is the church on this map?

There is mosques in the center of the city if I remember correctly.

**Comment by MoreKat** [comment]
Very nice, detailed map with a lot of height variation. I agree with JostP about the mosque, maybe turn it into some kind of palace, shouldn't be too much work. I noticed that there are a bit less ores in the mine on the blue side so you might want to change that as well, along with the obsidian doors and wooden signs in the map, as CTF doesn't support them. Chest zones and map.conf look fine.

**Comment by JostP** [comment]
Feel free to re-open this PR when you do the changes.

**Pull request closed without merging**
