### PR TITLE
Pyramids of Akmanrah

### PR DESCRIPTION
**Pull request by Alone0ne**

### CODE REVIEW

**Comment by MinetestSam** [comment]
You need to fix the names of the files. For example, the file containing the schematic should be map.mts. Likewise, screenshot containing file should be screenshot.png and config file should be map.conf

**Comment by Alone0ne** [comment]
just extract the zip file,you will find all the required files (in names preferrred )in a folder,its just a zipped file

**Comment by MinetestSam** [comment]
> just extract the zip file,you will find all the required files (in names preferrred )in a folder,its just a zipped file

Sorry but that isn't the job of the map reviewer.

**Comment by JostP** [comment]
I wanted to test your map today, but since `.conf` file is invalid, I can't do it. Check other map's `.conf` files to find an issue in yours.

Also, please, before making a PR, test map as singleplayer in CTF game. PR must contain `map.mts`, `map.conf` and `screenshot.png`.

Screenshot should show whole map from air and not only one pyramid like your screenshot.

**Comment by JostP** [comment]
continue in #167

**Pull request closed without merging**
