### PR TITLE
Add "King of The Hill" map!

### PR DESCRIPTION
**Pull request by moreavy**
Aopted from #196

### CODE REVIEW

**Comment by moreavy** [comment]
@Moomoodude your map has bugs.

**Review by Panquesito7 — COMMENTED** [review]
A screenshot is missing.

**Comment by moreavy** [comment]
> A screenshot is missing.

@Panquesito7 Screenshot temporarily missing because this map has bugs.

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please mark this PR as a draft if it's still WIP.

**Pull request closed without merging**
