### PR TITLE
Add "Broken Mountains" by Enrico

### PR DESCRIPTION
**Pull request by Enrikoo**
I going to request pull for my map here, take a look at it.

Hi guys
I made my first map, it is called Broken Mountains. It looks like Desert Spikes but without desert nodes.
When you spawn in the map. You will get 30 cobblestone to forward bridge or bridge up from the surface. You will not find any mese, diamond or apples (apples can be gained in chests), so the gameplay should be fine.
screenshot_20190207_135121

### CODE REVIEW

**Comment by Enrikoo** [comment]
**Minor Update**
- replace wooden pickaxe with stone pickaxe

[broken_mountains.zip](https://github.com/MT-CTF/maps/files/2847843/broken_mountains.zip)

**Comment by Enrikoo** [comment]
**Minor+ Update Broken Mountains**

- replace wooden sword with stone sword
- you will get 40 cobble stone instead 30 if you get respawned

[broken_mountains.zip](https://github.com/MT-CTF/maps/files/2848047/broken_mountains.zip)

**Comment by MinetestSam** [comment]
New interesting style of map with mountains. Everything looks and works good.

Gets my approval 👍

**Comment by ClobberXD** [comment]
Good thing players spawn with cobbles, but even so, there's only one place in the map where a player can come back up, which is on the red side (or blue, I forgot). So if a player is out of cobblestones, they'd essentially have to commit suicide to get back in the game. To compare, Desert spikes has a little more climbable terrain, instead of near-vertical plateaus. I'm not sure what is to be done here other than manually terraforming the whole place, but at least the players can be given a larger stack of cobbles as a workaround.

**Comment by MinetestSam** [comment]
Or rather maybe make a staircase around the mountains which lead to the top.

**Comment by Enrikoo** [comment]
Players should not commit suicide. They can take sand from the surface and climb up to the mountains.

I'll make small update which only conf will change.

**Comment by Enrikoo** [comment]
**Minor Update Broken Mountains**

- you will get 30 sticks if you will be respawned (used to make ladders to prevent suicide)

[broken_mountains.zip](https://github.com/MT-CTF/maps/files/2861180/broken_mountains.zip)

**Comment by BrianGaucher** [comment]
Quick suggestion, to let players climb up the cliffs, since stair cases don't quite mathc the style. Why not add some ladders on the cliffs near the start. Also, 30 sticks lets players build 28 ladders.

**Comment by Enrikoo** [comment]
Ugh, I dont have a saved map where I can fix it. Sorry... I maybe can try to do some changes.

**Comment by BrianGaucher** [comment]
> Ugh, I dont have a saved map where I can fix it. Sorry... I maybe can try to do some changes.

Yeah, well, using World Edit has commands //mtschemplace, '//set pos' and //mtschemcreate. I suggest reading the docs on them, if you need help, I'll be pleased to help.

**Comment by ClobberXD** [comment]
We already have Desert Spikes, is it worth having another map that is the same as the former but without the desert nodes? Even the OP asserts the map's uncanny resemblance to DS in the first post.

**Comment by Thomas--S** [comment]
I also doubt players would enjoy playing on this map. Desert Spikes is also quite unpopular.

**Comment by ClobberXD** [comment]
Closing as this is too similar to DS.

**Pull request closed without merging**
