### PR TITLE
Lava Puddles Update!

### PR DESCRIPTION
**Pull request by Avyukt1**
image

### CODE REVIEW

**Review by Panquesito7 — COMMENTED** [review]
Screenshot is up to 1MB. We should reduce its size without losing quality.
We can use this method from a PR in Mesecons: https://github.com/minetest-mods/mesecons/pull/464

**Comment by Avyukt1** [comment]
> Screenshot is up to 1MB. We should reduce its size without losing quality.
> We can use this method from a PR in Mesecons: [minetest-mods/mesecons#464](https://github.com/minetest-mods/mesecons/pull/464)

@Panquesito7 
I just pressed `F12` there.

**Comment by Avyukt1** [comment]
Don't merge this till I tell, I still have to do many things.

**Comment by Avyukt1** [comment]
I'll create a new Pull for this, This branch has been corrupted.

**Pull request closed without merging**
