### PR TITLE
Add new map "Coral Street Bridge" by Anonomous

### PR DESCRIPTION
**Pull request by AnonomousAccount**
**This is the second PR. The last one was closed due to GitHub shenanigans**

Issues posed by map testers on last PR:

- Map is too thin

### CODE REVIEW

**Comment by AnonomousAccount** [comment]
This map is kinda similar to the newly-merged Golden Gate Bridge, though I believe the experience will be pretty different. PVP will be more centralized and speedrunning should be less common.

**Comment by HobbitPower** [comment]
Continuation from #339

**Comment by HobbitPower** [comment]
Tested it with the latest CTF versions (Github and CDB): https://discord.com/channels/447819017391046687/448136831385468930/1268538815971197000
Maybe more will test the map and share their experience with this.

Nicely built otherwise, but honestly very similar concept to the Golden Gate Map.

**Comment by LuismiInTheZone** [comment]
You forgot to add the license. Did you change the .conf file by yourself? Because the license part doesn't appear

**Comment by LuismiInTheZone** [comment]
I have the same problem as HP, I don't know why. My opinion is that the map is fine, but I would light up the part under the bridge. Another thing is that in some vehicles some of the blocks are indestructible and others destructible. I recommend choosing one or other. Also, if you want, it is advisable to expand the chests around the map as well. The map is very similar to the Golden Gate Bridge, so it could have problems in the future.

**Comment by LuismiInTheZone** [comment]
Try to export the map again without changing anything (only the necessaries and things to change) and put the map again

**Comment by LuismiInTheZone** [comment]
> I have the same problem as HP, I don't know why. My opinion is that the map is fine, but I would light up the part under the bridge. Another thing is that in some vehicles some of the blocks are indestructible and others destructible. I recommend choosing one or other. Also, if you want, it is advisable to expand the chests around the map as well. The map is very similar to the Golden Gate Bridge, so it could have problems in the future.

Also, please remove the chest you put by yourself in the small boat, it can cause problems

**Comment by AnonomousAccount** [comment]
Unfortunatly, this map was too similar to another map

**Pull request closed without merging**
