### PR TITLE
Add new map "Coral Street Bridge"

### PR DESCRIPTION
**Pull request by AnonomousAccount**
Ummmm ignore all the commits except for the last one.
It's basically just all from my other PR, and then removing those files
Edit: This map is currently WIP, I have a buncha gameplay problems to fix, suggestions apreciated

### CODE REVIEW

**Comment by SoulS33ker** [comment]
**PR files** 
1.mts ✔
2.conf ; hint : ore-->ores ✘
3.screenshot 3:2 ✘
**Map**
1.errors ✔
2.chests✔
3.barriers✔
4.flags✔
**Mechanics**
1.equal chance ✔
2.base pos ✘ (opinion)
3.terrain balance ✔
4,ore count ✔

**Comment by AnonomousAccount** [comment]
SoulSeeker's Issues fixed

**Comment by SoulS33ker** [comment]
### **Improvement opinions**
### main concerns:
**1**.map looks too simple
**2**.low map width(too narrow)
**3**.coral & street not detected
### suggestions:
**1**.add a street
**2**.double the width of map
    -A possible way is to world edit 'copy' the existing structures & 'paste' side to side
       this could possibly open up 2 alternate base positions :
         A.between 2 bridges (centered to map)(new bridge created/copied by the way)
         B.green base at end of one bridge& orange at second bridge end
**3**.add street(a public road in a city, town, or village, typically with houses and buildings on one or both sides)
       (i)so add a village/city as per your skills rather than the plain hills
       (ii)possibly making the river banks cobble paved (of a piece of ground, covered with flat stones or bricks)
   An overall build quality improvement suggested as in examples above.

**Comment by AnonomousAccount** [comment]
The narrowness and the simplicity are done on purpose, so PVP is centralized only on the bridge

**Comment by AnonomousAccount** [comment]
Also, Coral Street is just a name, "Bridge" was already taken

**Comment by Themostrandom** [comment]
Hello, I've tested your map and I really like it. There are several possible attacks (the bridges, the arches and the underside). However, I've noticed some problems, mainly aesthetic: the cliffs are unrealistic in my opinion, and so are the entrances to the chest areas. I also noticed some inconsistencies with the car blocks (destructible, non-destructible). I'd advise you to make them 100% destructible, as some of the blocks you've used don't have a ctf_map: variant.
screenshot_20240614_141911
screenshot_20240614_141912
screenshot_20240614_141915
screenshot_20240614_141919
screenshot_20240614_141920
screenshot_20240614_141932
screenshot_20240614_141932_1
screenshot_20240614_142002
screenshot_20240614_142005
screenshot_20240614_142008
screenshot_20240614_142111

**Comment by AnonomousAccount** [comment]
Each block on each vehicle was placed with a purpose, most of them, you can break in at some parts (like the windows), but the main frame part is unbreakable

**Comment by AnonomousAccount** [comment]
Currently still working on this, ideas and more feedback appreciated

**Comment by ScaleRaker** [comment]
Looked at the map. Not too much to say honestly. The stuff that I was going to say has already been said. I really like the map personally and look forward to seeing it in-game. Sorry that my review is not very good, but I couldn't think of any other things other than what has already been mentioned by themostrandom01 and SoulSeeker.

**Pull request closed without merging**
