### PR TITLE
Add more chest on bridge map 

### PR DESCRIPTION
**Pull request by Themostrandom**
- [ x ] This PR has been tested locally
- Suggestion : https://discord.com/channels/447819017391046687/1008040841102766153/1253879184233730058

### CODE REVIEW

**Comment by LuismiInTheZone** [comment]
What was the result of the suggestion for curiosity, that I’m not currently at the discord

**Comment by AnonomousAccount** [comment]
> Out of curiosity, what was the result of the suggestion? that I’m not currently at the CTF discord

pretty positive, 12-3, though players always like when there are more chests

**Comment by HobbitPower** [comment]
If a PR, then it should be divided into two chest zones (30 chest per side).

**Comment by Themostrandom** [comment]
I allowed myself several things: remove the excess map (outside the map surface) put 30 chests per zone and make sure they don't appear in the water (I'm not sure about that).

**Comment by HobbitPower** [comment]
You removed the modes for the map. Also:
image

**Comment by Themostrandom** [comment]
> You removed the modes for the map. Also: image

I don't have this :/

**Comment by Themostrandom** [comment]
@HobbitPower its okay now
I fix bug and add ctf_map:ind_water and ctf_map:ind_stone_red

**Comment by HobbitPower** [comment]
Everything seems to be working. The screenshot is a bit outdated now, but I don't think we need to adjust that. ^^
Approved.

**Comment by Themostrandom** [comment]
> Everything seems to be working. The screenshot is a bit outdated now, but I don't think we need to adjust that. ^^ Approved.

That realy need an other approval ?

**Review by HobbitPower — APPROVED** [review]

**Pull request merged**
