### PR TITLE
Make it possible to get out of the pits without blocks in Water Academy

### PR DESCRIPTION
**Pull request by a-blob**
This PR makes a slice of the stone wall of the pit (the slice nearest to the flag) breakable so that players inside the pits with no blocks can dig out.

### CODE REVIEW

**Comment by HobbitPower** [comment]
@a-blob I haven't worked with it much myself, but you could also replace the red barrier glass in the ocean with the new water barriers (blue barrier glass). If you want to do this, let me know.

**Comment by a-blob** [comment]
> @a-blob I haven't worked with it much myself, but you could also replace the red barrier glass in the ocean with the new water barriers (blue barrier glass). If you want to do this, let me know.

Sure, I'll do that.

**Comment by a-blob** [comment]
@HobbitPower Done, but now there's a conflict.

**Comment by a-blob** [comment]
Conflict solved.

**Review by HobbitPower — APPROVED** [review]

**Pull request merged**
