### PR TITLE
04_iceage: Add a winter-land skybox

### PR DESCRIPTION
**Pull request by ClobberXD**
Attribution for skybox textures present in the `license` map meta field.

screenshot_20191012_110115

screenshot_20191012_110126

### CODE REVIEW

**Comment by ClobberXD** [comment]
MT-CTF/capturetheflag#471 merged. PR now ready for review.

**Comment by ClobberXD** [comment]
MT-CTF/capturetheflag#471 merged. PR now ready for review.

**Comment by rubenwardy** [comment]
What does this skybox look like at ground level? From the screenshots, it looks like the details are far to close and near rather than distant

**Comment by JostP** [comment]
What I need to do to test skybox?
Zaslonska slika 2019-10-29 12-01-00

**Comment by ClobberXD** [comment]
@JostP You'll have to run `update.sh` in CTF's root directory, after checking out the `iceage_skybox` branch of the `maps` submodule, which will copy the skybox textures from `ctf_map/maps` to `ctf_map/textures`. This is because only the textures in a mod's `textures/` sub-dir will be sent to the clients when connecting.

**Comment by Thomas--S** [comment]
I'm strongly opposed to adding `CC BY-NC 3.0` stuff. Non-commercial licenses don't match the open source criteria.

Please note: I am not a lawyer.

**Comment by JostP** [comment]
This is night?

Zaslonska slika 2019-10-29 14-13-09

**Comment by ClobberXD** [comment]
@Thomas--S Just read up on that license, you're right about `CC BY-NC` not being a true open source license. I'll look for another skybox then.

@JostP That's right. Also, thanks for reminding me to set `time_speed` and `start_time`. ;)

**Comment by MinetestSam** [comment]
Rebase needed and here is a site I found which lets you search up skyboxes with respect to their licence.
https://opengameart.org/art-search-advanced?field_art_tags_tid=skybox

**Comment by ClobberXD** [comment]
Thanks for the link, @MinetestSam. I was browsing the winter skyboxes section the other day, but I don't have the time to get a new skybox and apply it properly, after fixing all the rotation issues. I'm afraid this'll have to wait until mid-December.

**Comment by ClobberXD** [comment]
Closing due to inactivity. Can be re-opened on progress.

**Pull request closed without merging**
