### PR TITLE
Improve "river valley"

### PR DESCRIPTION
**Pull request by JostP**
Small improvement.
Added 4 watch towers on hills, can be used by snipers who will use snipers from incoming sniper mod.
Tested, works
Screenshot:
Zaslonska slika 2019-11-05 09-18-36

### CODE REVIEW

**Comment by JostP** [comment]
There's no need to hurry with reviewing, but it would be nice if we have this map in CTF v2

**Comment by JostP** [comment]
Thanks, this PR needs only one approval, doesn't it?

**Comment by MinetestSam** [comment]
I think it requires two approvals as it isn't a minor enhancement (I may be wrong here).

**Comment by Thomas--S** [comment]
A PR like this usually requires two approvals. I try to review this next weekend.

**Comment by ClobberXD** [comment]
I agree with MTSam - I'm not too happy about the same tower being used in multiple maps. I'm OK with the concept of a watchtower, but I'd really like to see a tower with a different blueprint or different nodes used.

**Comment by JostP** [comment]
Ok, I will change them

**Comment by MinetestSam** [comment]
Directory change needed.

**Comment by JostP** [comment]
Update: new watch towers design, fixed directory structure 
Tested, ready for re-review

**Comment by JostP** [comment]
continuation: #75

**Pull request closed without merging**
