### PR TITLE
Two Bases Two Teams Let's PvP

### PR DESCRIPTION
**Pull request by leolegPremiumPlus**
Finisehd ;) A BIG thanks to ScaleKRaker :D

### CODE REVIEW

**Comment by HobbitPower** [comment]
@leolegPremiumPlus There will be more detailed feedback in the future, but you might want to think of a different name. The name is quite long and not meaningful and could refer to any 2-team map. 
You should also adapt the folder name as soon as you have found a new name and shorten it considerably. You can customize it yourself via Github (see [here](https://github.com/MT-CTF/maps/pull/310#issuecomment-1718862789)) or it would be easier if you create a new PR. Perhaps @ScaleRaker can also help you with this.

**Comment by leolegPremiumPlus** [comment]
> @leolegPremiumPlus There will be more detailed feedback in the future, but you might want to think of a different name. The name is quite long and not meaningful and could refer to any 2-team map. You should also adapt the folder name as soon as you have found a new name and shorten it considerably. You can customize it yourself via Github (You can find a short explanation [here](https://github.com/MT-CTF/maps/pull/310#issuecomment-1718862789), you have to use your own fork and branch respectively.) or it would be easier if you create a new PR. Perhaps @ScaleRaker can also help you with this.

Do you think "Kingdoms war : red vs blue" or "Game of kingdoms" is good ?

**Comment by leolegPremiumPlus** [comment]
i think Game of Kingdoms is crazy xD

**Comment by Themostrandom** [comment]
Several comments:
The name is too long, like the underlined Hobbit
I think the addition of more standards would add rp
I would reduce the number of plants and flowers, it's beautiful but to put blocks it's disturbing
Some areas are empty (under the house)
There's a hole in the attic on both sides (inside).
For my part, I think there's a lack of items in the chests to be able to pvp as the name of your map indicates.
There's a hole in the ground on the river side 
There's a hole in the roof of the towers (no problem, either fill it in or make it bigger).
The underside of the map is not made of indestructible block.


I like your map overall despite these problems, it reminds me in general configuration my map arena pvp which is in review :)

**Comment by Themostrandom** [comment]
Because you are french : 
Plusieurs remarques :
Le nom est trop long comme la souligné Hobbit
Je penses que l'ajout de plus d’étendard ajouterais du rp
Je réduirais le nombre de plante et fleurs, c'est beau mais pour poser des blocks cela est dérangeant
Certaines zones sont vides (sous la maison)
Il y a un trou dans le grenier des deux coté (a l'interieur)
Pour ma part je pense qu'il manque d'item dans les coffres pour pouvoir pvp comme le nom de votre map l'indique.
Il y a un trou dans le sol coté rivière 
Il y a un trou dans le toit des tour (pas genant, soit le combler soit l'agrandir)
Le dessous de la map n'est pas en block indestructible


J'aime bien votre map dans l'ensemble malgré ces problèmes, elle me rapelle dans la configuration général ma map arena pvp qui est en review :)

**Comment by HobbitPower** [comment]
> i think Game of Kingdoms is crazy xD

It's better than the current one, for sure

**Comment by ScaleRaker** [comment]
I agree that the name should be changed. I'm not really sure what you mean by "standards" per say. One of the things that I wanted to do with this map was to make it harder for players to pillar, hence adding all the vegetation. leoleg can decide what to do with this one. The empty areas under the base I commented on myself but I did not I didn't do anything about because I didn't think of really anything to put there. Something should definitely go there though. The hole in the attic pertains to the same situation. I'm not really sure what you mean by "lack of items" to pvp with. AFAIK, nothing has changed with the chests. The holes as well as the bottom of the map being destructable are definitely my fault and are an oversight which should be able to be easily fixed. Unfortunately, it's unlikely that I will be able to work on this map for a while, but when I can, I'll try to fix the problems.

**Pull request closed without merging**
