### PR TITLE
"Lava Puddles" by smugler5

### PR DESCRIPTION
**Pull request by winniepee**
please test this map

### CODE REVIEW

**Comment by Avyukt1** [comment]
how to test this map?
What is the link to download the tester.
What are the steps to test the ctf map?

**Comment by Elvis-26** [comment]
@Avyukt1 35 diamonds!!! Bad idea to put very more diamonds. BUG with red barrier again. Please make not more diamonds and fix bug. Thanks

**Comment by Avyukt1** [comment]
> with

Fixed the issue

**Comment by winniepee** [comment]
need a new screenshot

**Comment by Avyukt1** [comment]
done a new screenshot

**Comment by Avyukt1** [comment]
pls reply,
what next to do?
or you didn't like my map?

**Comment by olliy1or** [comment]
there are no license

**Comment by olliy1or** [comment]
after few test the barriers seem broken, the actual barrier is invisible the barrier you put stays after the match starts

**Comment by Avyukt1** [comment]
Yes,
The map has errors.
I will fix it on Thursday.

**Comment by JostP** [comment]
Add license for your map.

**Comment by Avyukt1** [comment]
what is a license?

**Comment by Avyukt1** [comment]
and how to add it?

**Comment by JostP** [comment]
Choose one free software/opensource license.
https://github.com/MT-CTF/capturetheflag/tree/master/mods/ctf/ctf_map/map_maker#license

**Comment by Avyukt1** [comment]
Yes!
I have given an open license to the map.
Also I have clicked a new screenshot

**Comment by Avyukt1** [comment]
Hey,
There is a problem in the software of the map.
There are problems like
> flags are not in their position
> the barrier doesn't work
> Is there a one more way?

**Comment by olliy1or** [comment]
use one PR for each map

**Comment by Avyukt1** [comment]
okay,
thanks,
bye

**Comment by AnyBlue** [comment]
@winniepee There is 6 files changed. Delete the mulu hills

**Comment by Avyukt1** [comment]
sorry,
I have made the barrier in Z=0.
I will make the Changes quick

**Comment by Avyukt1** [comment]
In the next 48 hours, I will make the changes and soon will make it ready.

**Comment by Avyukt1** [comment]
Done with fixing bungs and now it is ready.

**Comment by Avyukt1** [comment]
Please test the map. I have tested this map and now it is working properly.
Go to https://github.com/Avyukt1/Lava-Puddles-Map to download and test it.

**Comment by Avyukt1** [comment]
@winniepee Why have you added mulu_hills map.conf and map.mts in this PR. That has also replaced my screnshot.png file.

**Pull request closed without merging**
