### PR TITLE
Add "Brookland"

### PR DESCRIPTION
**Pull request by JostP**
(This pull request was generated by a script)

### CODE REVIEW

**Comment by Avyukt1** [comment]
Did the team like my map?

**Comment by JostP** [comment]
They say it doesn't work, but I haven't tested it yet.
Have you tested it in CTF game?

**Comment by Avyukt1** [comment]
> They say it doesn't work, but I haven't tested it yet.
> Have you tested it in CTF game?

How to test in CTF Game?

**Comment by JostP** [comment]
Add license for your map.

**Comment by JostP** [comment]
Zaslonska slika 2020-11-04 18-54-57

Sorry but this map is veeeeeeery plain, and server already has to many of plain maps. CTF team agree to don't add this map. Note that plain maps are usually boring and players has nowhere to hide.

**Pull request closed without merging**
