### PR TITLE
Add an ammo pack as initial item on abandoned isles

### PR DESCRIPTION
**Pull request by MinetestSam**

### CODE REVIEW

**Comment by ClobberXD** [comment]
What's better than adding an ammo-pack as part of `initial_stuff`? Adding two of them, of course! :D

**Comment by MinetestSam** [comment]
There were mixed replies, Xenon wanted only one ammo pack on the map. So open to debate and discussions.

**Comment by JostP** [comment]
I think 1 is enough IMO as pistol usually doesn't even need an ammo (you die faster than spending all gun's life (life or however it is called) ;) )

**Comment by Thomas--S** [comment]
I didn't play on this map yet, but I'd suggest to start with adding one and see if it is enough. A second one can be added later if necessary.

**Comment by JostP** [comment]
Tested, works. Should I merge or wait discussion of adding one ammo to end?

**Comment by ClobberXD** [comment]
He he he :smiling_imp:

**Pull request merged**
