### PR TITLE
King of the Hill

### PR DESCRIPTION
**Pull request by MoomooDude**
2nd map made by me, first time doing this by myself so if i messed something up tell me.

https://github.com/MoomooDude/King-of-the-Hill

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please make a pull request per map. Also, the beach map is missing a license. I recommend [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/). Also, why are the screenshots on the root directory? Why is there a `map.conf` file in the root directory? All these issues should be fixed.

**Comment by MoomooDude** [comment]
> Please make a pull request per map. Also, the beach map is missing a license. I recommend [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/). Also, why are the screenshots on the root directory? Why is there a `map.conf` file in the root directory? All these issues should be fixed.

I didn't mean to submit the beach map, just the king of the hill map.

**Review by moreavy — COMMENTED** [review]
You have made 33 files changes. Do you know how to create Pull Requests or should I create for you?

**Comment by MoomooDude** [comment]
> You have made 33 files changes. Do you know how to create Pull Requests or should I create for you?

I have no clue how to make them. I tried my best. I'm at my grandparents for 2 days I will try and fix it on Monday or Tuesday

**Comment by moreavy** [comment]
@MoomooDude I will create a Pull for you. You don't need to take effort :wink:

**Comment by JostP** [comment]
> MoomooDude I will create a Pull for you. You don't need to take effort wink

@moreavy  Still want to make adoption PR?

**Comment by moreavy** [comment]
Probably waiting for MoomooDude's reply.

**Comment by moreavy** [comment]
@MoomooDude choose a license.

**Pull request closed without merging**
