### PR TITLE
Monolithic mountains

### PR DESCRIPTION
**Pull request by ClobberXD**
**Author**: Brian Gaucher

### CODE REVIEW

**Comment by ClobberXD** [comment]
- Large region at the bottom of the map missing a floor.
- Glass panes, and mese post lights aren't supported in CTF. Needs to be removed. Note that wool might be supported in the near future.
- **.conf**:
  - There are two red teams in conf.
  - There shouldn't be any spaces between the x, y, and z coords. e.g. `team.1.pos = 38,56,15`

**Comment by ClobberXD** [comment]
I've fixed map's conf file myself. Hopefully, the author remembers to address the shortcomings of the schem itself.

**Comment by ClobberXD** [comment]
@BrianGaucher Are you interested in finishing your map?

**Comment by BrianGaucher** [comment]
Yeah, I'll get around to it eventually. I currently have grade 12 exams. A bit busy. Sorry for having forgotten, thanks for reminding me.
I'm planning on restarting the map. I learned a lot the first time I tried. And it was my first time using world-edit.
I'll use the same seed, same mountain. But have a more consistent design. I'll fill up caves with stones, hide ores in the ground and make my buildings with only supported materials. And no airships. I'll also make sure it's a tiny bit more even (just small patches).

Should I try finishing for the end of January?

On January 14, 2019 2:13:08 AM EST, ClobberXD <notifications@github.com> wrote:
>@BrianGaucher Are you interested in finishing your map?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/MT-CTF/maps/pull/4#issuecomment-453917044

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ClobberXD** [comment]
No problem, I can understand. There's no hurry. :)

If you're planning to make a new map, make sure you have the updated version of the `ctf_map` mod, as it has gone through quite a few notable updates lately.

**Comment by ClobberXD** [comment]
Closing as author is starting from scratch again.

**Pull request closed without merging**
