### PR TITLE
Green Hills Map by DiamondPlane

### PR DESCRIPTION
**Pull request by Toby1710**
New map

### CODE REVIEW

**Review by Panquesito7 — COMMENTED** [review]
Screenshot looks nice. Where is red and blue bases, though?

**Comment by AnyBlue** [comment]
> Screenshot looks nice. Where is red and blue bases, though?

What do you mean? You mean no bases on screenshot?

**Comment by Panquesito7** [comment]
I do not distinguish what base is red and blue. Never mind about that. 😄

**Review by Avyukt1 — APPROVED** [review]

**Comment by MoreKat** [comment]
Good map with a lot of variation, different from the existing maps as well. Everything seems fine, no errors. The building on top of the mountain is an amazing sniper post :)

**Comment by Avyukt1** [comment]
True, Please merge soon.

**Comment by AnyBlue** [comment]
> Good map with a lot of variation, different from the existing maps as well. Everything seems fine, no errors. The building on top of the mountain is an amazing sniper post :)

Thanks! Are you Kat? :)

**Review by Avyukt1 — APPROVED** [review]

**Review by Panquesito7 — APPROVED** [review]
Didn't test, but everything LGTM. Screenshot looks pretty nice! 👍

**Review by JostP — APPROVED** [review]
Nice map :+1:
No bugs found.
The fort on the top of the hill is on one side of the barrier, but it is not that big issue.

Did you leave so much unneeded area outside of the barrier on purpose? Tell me if you want to reduce area outside of the barrier or not. Approving in current state, but you can still remove it because it could cause more lag (bigger map = more lag on weak computers).
Zaslonska slika 2021-01-16 12-56-49

**Comment by JostP** [comment]
Will merge after map voting.

**Comment by Avyukt1** [comment]
image
image
image
image
image
These are a few screenshots of the map.

**Pull request merged**
