### PR TITLE
Add "Abandoned Isles" map by gimp

### PR DESCRIPTION
**Pull request by mrowlbio**
I made the paths indestructible.

I will deal with the custom chest zones later, The map is done, can you add it so we can get feedback on how it plays, then I will do the chest zones.

### CODE REVIEW

**Comment by Thomas--S** [comment]
Previous comments are in #3

**Comment by xenonca** [comment]
Tested it, seems a nice new map to play!

**Comment by JostP** [comment]
I can make chest zones for you if you want. It is not so hard and it would be good if there were enough chests. I am away this week, I can make it next week.

**Comment by ClobberXD** [comment]
Sorry for the late review. Here are my thoughts:

1) Map looks pretty good overall.
2) There's a severe lack of chests as already noted.
3) Players are given 50 sandstones by default, but they aren't provided with tool(s) to break them?

I can cope with 2, as long as 3 is fixed - i.e. a steel pick should be provided by default. I'd still prefer custom chest zones in the long-term though.

**Comment by ClobberXD** [comment]
@mrowlbio You around? Are you still interested in taking up this PR?

**Comment by ClobberXD** [comment]
Continued in #52

**Pull request closed without merging**
